/* APS_LOGIN_V2_BEGIN */
(function(){
const css=`
.aps-login-v2{min-height:100vh;display:grid;grid-template-columns:minmax(0,1.14fr) minmax(440px,.86fr);background:linear-gradient(145deg,#fff 0%,#fff9fa 48%,#f6f7fa 100%);color:#101827;overflow:hidden;font-family:Inter,ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}
.aps-v2-left{position:relative;min-height:100vh;padding:48px 5vw 42px;overflow:hidden;display:flex;flex-direction:column;background:radial-gradient(circle at 62% 44%,#ffe1e7 0,transparent 34%),linear-gradient(145deg,#fff 0%,#fff7f8 72%,#ffecef 100%)}
.aps-v2-left:after{content:"";position:absolute;left:-12%;right:-3%;bottom:-125px;height:260px;background:linear-gradient(100deg,#f4516c,#dc163a 58%,#a80728);border-radius:50% 50% 0 0/28% 28% 0 0;transform:rotate(-2deg);opacity:.96}
.aps-v2-brand{position:relative;z-index:5;display:flex;align-items:center;gap:13px;color:#d7193f;text-transform:uppercase;font-size:18px;line-height:1.05}.aps-v2-star{width:55px;height:55px;display:grid;place-items:center;color:#fff;background:linear-gradient(145deg,#ed274b,#b90728);clip-path:polygon(50% 0,61% 34%,98% 34%,68% 55%,79% 91%,50% 69%,21% 91%,32% 55%,2% 34%,39% 34%);font-weight:950;font-size:12px}.aps-v2-brand b{display:block;font-size:27px;letter-spacing:-.03em}
.aps-v2-copy{position:relative;z-index:5;width:min(49%,620px);margin:auto 0 7vh}.aps-v2-copy h1{font-size:clamp(54px,5.45vw,84px);line-height:.96;letter-spacing:-.06em;margin:0 0 24px;font-weight:900}.aps-v2-copy h1 em{font-style:normal;color:#d7193f}.aps-v2-copy p{font-size:clamp(17px,1.55vw,22px);line-height:1.52;color:#515c6d;max-width:440px;margin:0 0 34px}.aps-v2-rule{width:78px;height:4px;border-radius:20px;background:#df2546;margin:0 0 25px}.aps-v2-tagline{display:flex;align-items:center;gap:12px;color:#c41335;font-weight:850;font-size:16px}.aps-v2-tagicon{width:48px;height:48px;border:2px solid #e12a49;border-radius:15px;display:grid;place-items:center;background:#fff9fa}
.aps-v2-photo{position:absolute;z-index:4;width:min(48vw,655px);height:min(48vw,655px);right:-4.5vw;bottom:-2.5vw;border-radius:50%;overflow:hidden;filter:drop-shadow(0 30px 50px #7d001c2b)}.aps-v2-photo img{width:100%;height:100%;object-fit:cover;border-radius:50%;display:block}
.aps-v2-right{min-height:100vh;display:grid;place-items:center;padding:38px 4.2vw;position:relative;z-index:8;background:linear-gradient(160deg,#fff9fa,#f6f7fa)}.aps-v2-card{width:min(550px,100%);background:#fffffff6;border:1px solid #fff;border-radius:35px;padding:39px 38px;box-shadow:0 28px 80px #5e0d1f1d}.aps-v2-lock{width:72px;height:72px;border-radius:50%;display:grid;place-items:center;margin:0 auto 18px;background:linear-gradient(145deg,#e61d42,#be0c2d);box-shadow:0 15px 30px #d7193f35;color:#fff;font-size:30px}.aps-v2-card h2{text-align:center;font-size:38px;letter-spacing:-.045em;margin:0 0 8px}.aps-v2-sub{text-align:center;color:#697386;font-size:15px;margin:0 0 30px}
.aps-v2-field{margin:18px 0}.aps-v2-field label{font-size:14px;font-weight:800;display:block;margin:0 0 8px}.aps-v2-control{height:61px;border:1.5px solid #e1e5eb;background:#fbfcfe;border-radius:17px;display:flex;align-items:center;padding:0 16px}.aps-v2-control:focus-within{border-color:#df526c;box-shadow:0 0 0 4px #fce9ed}.aps-v2-control span{font-size:18px;opacity:.58;margin-right:10px}.aps-v2-control input{border:0;background:transparent;outline:0;width:100%;font-size:15px;color:#1f2937;height:100%}.aps-v2-meta{display:flex;justify-content:space-between;align-items:center;margin:17px 1px 20px;font-size:13px;color:#5f6876}.aps-v2-meta label{display:flex;align-items:center;gap:8px}.aps-v2-meta input{accent-color:#d7193f;width:16px;height:16px}.aps-v2-forgot{border:0;background:transparent;color:#d7193f;font-weight:750;cursor:pointer}.aps-v2-submit{width:100%;height:60px;border:0;border-radius:17px;background:linear-gradient(135deg,#df1c40,#c00e30);color:#fff;font-size:16px;font-weight:900;box-shadow:0 14px 27px #d7193f31;cursor:pointer}.aps-v2-secure{margin-top:25px;border:1px solid #f0d4da;background:#fff7f9;border-radius:17px;padding:15px 17px;display:flex;gap:11px;color:#66707e;font-size:12px;line-height:1.45}.aps-v2-secure strong{color:#b30c2e}.aps-v2-notice{margin-bottom:16px;padding:12px 14px;border:1px solid #ffd3dc;background:#fff0f3;color:#a4122e;border-radius:13px;font-size:13px}
@media(max-width:1050px){.aps-login-v2{grid-template-columns:1fr}.aps-v2-left{min-height:330px;height:330px;padding:24px 22px}.aps-v2-copy{width:52%;margin:auto 0}.aps-v2-copy h1{font-size:46px}.aps-v2-copy p,.aps-v2-rule,.aps-v2-tagline{display:none}.aps-v2-photo{width:335px;height:335px;right:2vw;bottom:-35px}.aps-v2-right{min-height:auto;padding:18px 16px 36px}.aps-v2-card{padding:29px 24px;border-radius:28px}.aps-v2-card h2{font-size:31px}}
@media(max-width:620px){.aps-v2-left{height:270px;min-height:270px;padding:16px 14px}.aps-v2-brand{font-size:13px}.aps-v2-star{width:44px;height:44px}.aps-v2-brand b{font-size:21px}.aps-v2-copy{display:none}.aps-v2-photo{width:285px;height:285px;right:50%;transform:translateX(50%);bottom:-42px}.aps-v2-right{padding:16px 12px 28px}.aps-v2-card{padding:25px 19px}.aps-v2-lock{width:58px;height:58px;font-size:25px}.aps-v2-card h2{font-size:29px}.aps-v2-control,.aps-v2-submit{height:57px}}
`;
if(!document.getElementById('aps-login-v2-style')){const s=document.createElement('style');s.id='aps-login-v2-style';s.textContent=css;document.head.appendChild(s)}
renderLogin=function(msg=''){document.body.className='';const boot=document.getElementById('boot');if(boot)boot.classList.add('hide');const invite=new URLSearchParams(location.hash.replace(/^#/,''));if(invite.get('invite'))return renderInvite(invite);document.getElementById('root').innerHTML=`<div class="aps-login-v2"><section class="aps-v2-left"><div class="aps-v2-brand"><div class="aps-v2-star">APS</div><div>Campanha<b>APS</b></div></div><div class="aps-v2-copy"><h1>Bem-vindo à <em>Campanha APS</em></h1><div class="aps-v2-rule"></div><p>Equipe, agenda, ações, materiais, logística e finanças em um só lugar, com segurança e atualização em tempo real.</p><div class="aps-v2-tagline"><div class="aps-v2-tagicon">◇</div><div>Gestão inteligente.<br>Resultados reais.</div></div></div><div class="aps-v2-photo"><img src="https://soqhetmmhxyepzzcduaa.supabase.co/storage/v1/object/public/campanha-web/ana-paula-login.webp?v=20260828-final" alt="Ana Paula Siqueira"></div></section><section class="aps-v2-right"><form class="aps-v2-card" onsubmit="doLogin(event)"><div class="aps-v2-lock">🔒</div><h2>Acesse sua conta</h2><p class="aps-v2-sub">Entre com seu e-mail e senha para continuar.</p>${msg?`<div class="aps-v2-notice">${esc(msg)}</div>`:''}<div class="aps-v2-field"><label>E-mail</label><div class="aps-v2-control"><span>♙</span><input name="email" type="email" required autocomplete="username" value="coordenacao@campanhaaps.local"></div></div><div class="aps-v2-field"><label>Senha</label><div class="aps-v2-control"><span>▣</span><input name="password" type="password" required autocomplete="current-password"></div></div><div class="aps-v2-meta"><label><input type="checkbox" checked> Lembrar-me</label><button class="aps-v2-forgot" type="button" onclick="toast('Solicite a redefinição da senha à Coordenação Geral.')">Esqueceu sua senha?</button></div><button class="aps-v2-submit" type="submit">Entrar na plataforma &nbsp;→</button><div class="aps-v2-secure"><span>🛡️</span><div><strong>Acesso seguro.</strong><br>Cada integrante vê apenas os módulos permitidos para o seu perfil.</div></div></form></section></div>`};
})();
/* APS_LOGIN_V2_END */