import patch_v033_favorites
from pathlib import Path
import json


def replace_between(text,start_marker,end_marker,new_block,label):
    start=text.find(start_marker)
    end=text.find(end_marker,start)
    if start<0 or end<0:
        raise SystemExit(f'Missing v0.3.34 block: {label}')
    return text[:start]+new_block+text[end:]


def replace_once(text,old,new,label):
    if old not in text:
        raise SystemExit(f'Missing v0.3.34 target: {label}')
    return text.replace(old,new,1)

p=Path('AppV020.js')
text=p.read_text(encoding='utf-8')

# Bottom navigation: Apuracao becomes a primary tab; Comparar remains in the drawer.
text=replace_once(text,"const items=[['Início','⌂'],['Busca','⌕'],['Pesquisas','▥'],['Raio-X','X'],['Comparar','⇄']];","const items=[['Início','⌂'],['Busca','⌕'],['Raio-X','X'],['Pesquisas','▥'],['Apuração','◉']];",'bottom navigation')

# Make the existing Home Favorites quick action functional.
text=replace_once(text,"function Home({count,onRaioX,onSearch,onCompare})","function Home({count,onRaioX,onSearch,onCompare,onFavorites})",'Home signature')
text=replace_once(text,"<Quick icon=\"☆\" label={'Favoritos'} onPress={()=>{}}/>","<Quick icon=\"☆\" label={'Favoritos'} onPress={onFavorites}/>",'Home Favorites shortcut')
text=text.replace("<Home count={candidates.length} onRaioX={goRaioX} onSearch={()=>go('Busca')} onCompare={()=>go('Comparar')}/>","<Home count={candidates.length} onRaioX={goRaioX} onSearch={()=>go('Busca')} onCompare={()=>go('Comparar')} onFavorites={()=>go('Favoritos')}/>")

# Compact, clean poll bars with favorite highlighting.
pollbar=r'''function PollBar({name,party,pct,leader=false,favorite=false}){const s=useStyles();return <View style={{marginTop:11,padding:favorite?8:0,borderRadius:12,backgroundColor:favorite?'rgba(240,160,0,.08)':'transparent',borderWidth:favorite?1:0,borderColor:'rgba(240,160,0,.30)'}}><View style={{flexDirection:'row',justifyContent:'space-between',alignItems:'center',gap:8}}><View style={{flex:1,flexDirection:'row',alignItems:'center',gap:6}}><Text style={{color:s._text,fontWeight:'800',fontSize:12,flexShrink:1}} numberOfLines={1}>{name}{party?` (${party})`:''}</Text>{favorite?<View style={{paddingHorizontal:6,paddingVertical:2,borderRadius:7,backgroundColor:'rgba(240,160,0,.15)'}}><Text style={{color:'#C98000',fontSize:7,fontWeight:'900'}}>★ FAVORITO</Text></View>:leader?<View style={{paddingHorizontal:6,paddingVertical:2,borderRadius:7,borderWidth:1,borderColor:s._blue}}><Text style={{color:s._blue,fontSize:7,fontWeight:'900'}}>LIDERA</Text></View>:null}</View><Text style={{color:favorite?'#C98000':s._blue,fontWeight:'900',fontSize:14}}>{pct}%</Text></View><View style={{height:7,borderRadius:4,backgroundColor:s._surface2,overflow:'hidden',marginTop:5}}><View style={{height:'100%',width:`${Math.min(100,Math.max(2,Number(pct||0)*2.15))}%`,backgroundColor:favorite?'#E5A21A':s._blue,borderRadius:4}}/></View></View>}'''
text=replace_between(text,'function PollBar(','\nfunction PollCard(',pollbar,'PollBar')

# Cards match the approved light, compact dashboard hierarchy.
pollcard=r'''function PollCard({poll}){
  const s=useStyles();const {matchesName}=useFavorites();const badge=(poll.institute||'?').slice(0,1).toUpperCase();const purple=poll.institute==='Quaest';
  const labels={PRESIDENTE:'Presidente · 1º turno',GOVERNADOR:`Governador · ${poll.uf}`,SENADOR:`Senador · ${poll.uf}`,DEPUTADO_FEDERAL:`Deputado Federal · ${poll.uf}`,DEPUTADO_ESTADUAL:`Deputado Estadual · ${poll.uf}`,DEPUTADO_DISTRITAL:'Deputado Distrital · DF'};
  const officeLabel=labels[poll.office]||'Pesquisa eleitoral';
  return <View style={{backgroundColor:s._surface,borderWidth:1,borderColor:s._border,borderRadius:20,padding:15,shadowColor:'#00152F',shadowOpacity:.05,shadowRadius:10,shadowOffset:{width:0,height:4},elevation:2}}>
    <View style={{flexDirection:'row',alignItems:'center',justifyContent:'space-between',gap:9}}><View style={{flexDirection:'row',alignItems:'center',gap:10,flex:1}}><View style={{width:38,height:38,borderRadius:19,backgroundColor:purple?'#6F2DBD':s._blue,alignItems:'center',justifyContent:'center'}}><Text style={{color:'#fff',fontSize:19,fontWeight:'900'}}>{badge}</Text></View><View style={{flex:1}}><Text style={{color:s._text,fontSize:18,fontWeight:'900'}}>{poll.institute}</Text><Text style={{color:s._muted,fontSize:9,marginTop:1}}>{officeLabel}</Text></View></View><Text style={{color:s._blue,fontSize:9,fontWeight:'900'}}>{poll.published}</Text></View>
    <View style={{marginTop:12,paddingVertical:9,borderTopWidth:1,borderBottomWidth:1,borderColor:s._border}}>{poll.mode?<Text style={{color:s._blue,fontSize:8,fontWeight:'900',marginBottom:3}}>{String(poll.mode).toUpperCase()}</Text>:null}{poll.question?<Text style={{color:s._text,fontSize:9,lineHeight:13,marginBottom:5}}>{poll.question}</Text>:null}<Text style={{color:s._muted,fontSize:9,lineHeight:15}}>Campo: {poll.field||'—'}</Text><Text style={{color:s._muted,fontSize:9,lineHeight:15}}>Amostra: {Number(poll.sample||0).toLocaleString('pt-BR')}   ·   Margem: ±{poll.margin||0} p.p.</Text><Text style={{color:s._muted,fontSize:9,lineHeight:15}}>Registro TSE: {poll.registry||'—'}</Text></View>
    <View>{(poll.results||[]).map(([n,p,v],i)=><PollBar key={`${poll.id}-${n}`} name={n} party={p} pct={v} leader={i===0} favorite={matchesName(n,poll.office,poll.uf)}/>)}</View>
    {poll.sourceUrl?<TouchableOpacity onPress={()=>Linking.openURL(poll.sourceUrl)} style={{marginTop:13,paddingTop:11,borderTopWidth:1,borderTopColor:s._border,alignItems:'center'}}><Text style={{color:s._text,fontSize:10,fontWeight:'800'}}>Ver detalhes  ›</Text></TouchableOpacity>:null}
  </View>
}'''
text=replace_between(text,'function PollCard({poll})','\nfunction PollComparison(',pollcard,'PollCard')

comparison=r'''function PollComparison({polls,office='PRESIDENTE',uf='BR'}){
  const s=useStyles();const df=(polls||[]).find(p=>p.institute==='Datafolha'),qu=(polls||[]).find(p=>p.institute==='Quaest');if(!df||!qu)return null;
  const officeNames={PRESIDENTE:'Presidente',GOVERNADOR:`Governador · ${uf}`,SENADOR:`Senador · ${uf}`,DEPUTADO_FEDERAL:`Deputado Federal · ${uf}`,DEPUTADO_ESTADUAL:`Deputado Estadual · ${uf}`,DEPUTADO_DISTRITAL:'Deputado Distrital · DF'};
  const names=[...(df.results||[]).filter(r=>r[1]).slice(0,4).map(r=>r[0])];const get=(poll,name)=>poll?.results?.find(r=>r[0]===name)?.[2]??0;
  return <View style={{backgroundColor:s._surface,borderWidth:1,borderColor:s._border,borderRadius:20,padding:15,shadowColor:'#00152F',shadowOpacity:.05,shadowRadius:10,elevation:2}}><View style={{flexDirection:'row',alignItems:'center',justifyContent:'space-between',gap:8}}><View style={{flex:1}}><Text style={{color:s._text,fontSize:17,fontWeight:'900'}}>Comparativo — {officeNames[office]||office}</Text><Text style={{color:s._muted,fontSize:9,marginTop:2}}>Datafolha × Quaest · levantamentos mais recentes exibidos</Text></View><Text style={{color:s._blue,fontSize:21}}>▥</Text></View><View style={{flexDirection:'row',gap:12,marginTop:14}}>{[df,qu].map(poll=><View key={poll.institute} style={{flex:1,minWidth:0}}><View style={{flexDirection:'row',alignItems:'center',gap:7,marginBottom:8}}><View style={{width:28,height:28,borderRadius:14,backgroundColor:poll.institute==='Quaest'?'#6F2DBD':s._blue,alignItems:'center',justifyContent:'center'}}><Text style={{color:'#fff',fontSize:12,fontWeight:'900'}}>{poll.institute[0]}</Text></View><View style={{flex:1}}><Text style={{color:s._text,fontSize:10,fontWeight:'900'}}>{poll.institute}</Text><Text style={{color:s._muted,fontSize:7}}>{poll.published}</Text></View></View>{names.map(name=>{const pct=get(poll,name);return <View key={`${poll.institute}-${name}`} style={{marginTop:7}}><View style={{flexDirection:'row',justifyContent:'space-between',gap:5}}><Text style={{color:s._text,fontSize:8,fontWeight:'700',flex:1}} numberOfLines={1}>{name}</Text><Text style={{color:s._blue,fontSize:10,fontWeight:'900'}}>{pct}%</Text></View><View style={{height:5,borderRadius:3,backgroundColor:s._surface2,overflow:'hidden',marginTop:3}}><View style={{height:'100%',width:`${Math.min(100,Math.max(2,pct*2.15))}%`,backgroundColor:s._blue,borderRadius:3}}/></View></View>})}</View>)}</View><Text style={{color:s._muted,fontSize:7,lineHeight:11,marginTop:12}}>Compare instituto, período de campo, amostra e margem de erro. Percentuais de pesquisas diferentes não devem ser somados.</Text></View>
}'''
text=replace_between(text,'function PollComparison(','\nfunction PollsScreen(){',comparison,'PollComparison')

polls_screen=r'''function PollsScreen(){
  const s=useStyles();
  const [category,setCategory]=useState('PRESIDENTE'),[deputyKind,setDeputyKind]=useState('FEDERAL'),[uf,setUf]=useState('MG'),[source,setSource]=useState('Todas');
  const [locationPrompt,setLocationPrompt]=useState(false),[statePicker,setStatePicker]=useState(false),[locationBusy,setLocationBusy]=useState(false),[prefsReady,setPrefsReady]=useState(false),[locationDecision,setLocationDecision]=useState('');
  const UFS=[['AC','Acre'],['AL','Alagoas'],['AP','Amapá'],['AM','Amazonas'],['BA','Bahia'],['CE','Ceará'],['DF','Distrito Federal'],['ES','Espírito Santo'],['GO','Goiás'],['MA','Maranhão'],['MT','Mato Grosso'],['MS','Mato Grosso do Sul'],['MG','Minas Gerais'],['PA','Pará'],['PB','Paraíba'],['PR','Paraná'],['PE','Pernambuco'],['PI','Piauí'],['RJ','Rio de Janeiro'],['RN','Rio Grande do Norte'],['RS','Rio Grande do Sul'],['RO','Rondônia'],['RR','Roraima'],['SC','Santa Catarina'],['SP','São Paulo'],['SE','Sergipe'],['TO','Tocantins']];
  const UF_BY_NAME=Object.fromEntries(UFS.map(([code,name])=>[normalize(name),code]));const LOCATION_UF_KEY='raiox.polls.uf.v032',LOCATION_DECISION_KEY='raiox.polls.location.decision.v032';
  const MG_BOOTSTRAP=[{id:'df-mg-gov-2108',institute:'Datafolha',office:'GOVERNADOR',uf:'MG',published:'21/08/2026',field:'18 a 20/08/2026',sample:1204,margin:3,registry:'MG-00446/2026',sourceUrl:'https://www1.folha.uol.com.br/poder/2026/08/datafolha-cleitinho-lidera-disputa-em-mg-com-32-patrus-e-kalil-tem-12-cada.shtml',mode:'Estimulada',question:'Governador de Minas Gerais - 1º turno',results:[['Cleitinho Azevedo','Republicanos',32],['Patrus Ananias','PT',12],['Alexandre Kalil','PDT',12],['Mateus Simões','PSD',4],['Flávio Roscoe','PL',4],['Gabriel Azevedo','MDB',4],['Branco/Nulo','',14],['Indecisos','',13]]}];
  const [scopes,setScopes]=useState({'PRESIDENTE:BR':{polls:POLL_SNAPSHOT,updatedAt:null,note:''},'GOVERNADOR:MG':{polls:MG_BOOTSTRAP,updatedAt:null,note:'Última carga verificada; buscando atualização'}}),[syncingKey,setSyncingKey]=useState('');
  const appState=useRef(AppState.currentState),inFlight=useRef(new Set());
  const office=category==='DEPUTADOS'?(deputyKind==='FEDERAL'?'DEPUTADO_FEDERAL':uf==='DF'?'DEPUTADO_DISTRITAL':'DEPUTADO_ESTADUAL'):category;
  const scopeKey=(o=office,u=uf)=>o==='PRESIDENTE'?'PRESIDENTE:BR':`${o}:${String(u||'MG').toUpperCase().slice(0,2)}`;const cacheKey=k=>`${POLLS_CACHE_KEY}.${k}`,currentKey=scopeKey(),current=scopes[currentKey]||{polls:[],updatedAt:null,note:''};
  const saveScope=async(k,value)=>{try{await SecureStore.setItemAsync(cacheKey(k),JSON.stringify(value))}catch{}};const loadScope=async(k)=>{try{const raw=await SecureStore.getItemAsync(cacheKey(k));if(!raw)return null;const v=JSON.parse(raw);return Array.isArray(v?.polls)&&v.polls.length?v:null}catch{return null}};
  const setScope=async(k,polls,at,note)=>{if(!Array.isArray(polls)||!polls.length)return false;const value={polls,updatedAt:at||new Date().toISOString(),note:note||''};setScopes(prev=>({...prev,[k]:value}));await saveScope(k,value);return true};
  const refresh=async(nextOffice=office,nextUf=uf)=>{const o=nextOffice||'PRESIDENTE',u=o==='PRESIDENTE'?'BR':String(nextUf||'MG').toUpperCase().slice(0,2),k=scopeKey(o,u);if(inFlight.current.has(k))return;inFlight.current.add(k);setSyncingKey(k);setScopes(prev=>({...prev,[k]:{...(prev[k]||{polls:[],updatedAt:null}),note:'Atualizando…'}}));try{const r=await fetch(`${LIVE_POLLS_API}?office=${encodeURIComponent(o)}&uf=${encodeURIComponent(u)}&t=${Date.now()}`,{headers:{Accept:'application/json','Cache-Control':'no-cache'}});const data=await r.json().catch(()=>null);if(r.ok&&data?.ok&&Array.isArray(data.polls)&&data.polls.length){await setScope(k,data.polls,data.fetchedAt,data.fresh?'Atualizado agora':'Última carga válida mantida');return}setScopes(prev=>({...prev,[k]:{...(prev[k]||{polls:[],updatedAt:null}),updatedAt:data?.fetchedAt||prev[k]?.updatedAt||null,note:data?.warning||'Nenhuma pesquisa registrada e verificável encontrada.'}}))}catch{const cached=await loadScope(k);if(cached)setScopes(prev=>({...prev,[k]:{...cached,note:'Sem conexão; última carga válida mantida'}}));else setScopes(prev=>({...prev,[k]:{...(prev[k]||{polls:[],updatedAt:null}),note:'Sem conexão com as fontes'}}))}finally{inFlight.current.delete(k);setSyncingKey(v=>v===k?'':v)}};
  const markLocationDecision=async value=>{setLocationDecision(value);try{await SecureStore.setItemAsync(LOCATION_DECISION_KEY,value)}catch{}};const selectUf=async code=>{if(!UFS.some(([c])=>c===code))return;setUf(code);setStatePicker(false);setLocationPrompt(false);await markLocationDecision('manual');try{await SecureStore.setItemAsync(LOCATION_UF_KEY,code)}catch{}};
  const detectState=async()=>{if(locationBusy)return;setLocationBusy(true);try{const permission=await Location.requestForegroundPermissionsAsync();if(permission.status!=='granted'){await markLocationDecision('denied');setLocationPrompt(false);setStatePicker(true);return}const pos=await Location.getCurrentPositionAsync({accuracy:Location.Accuracy.Low});const places=await Location.reverseGeocodeAsync({latitude:pos.coords.latitude,longitude:pos.coords.longitude});const place=places?.[0]||{},country=normalize(place.isoCountryCode||place.country||'');let region=normalize(place.region||place.subregion||'').replace(/^ESTADO DE /,'').replace(/^STATE OF /,'');const detected=UF_BY_NAME[region]||(UFS.some(([c])=>c===region)?region:'');if(!detected||!(country==='BR'||country==='BRA'||country==='BRASIL'||country==='BRAZIL')){await markLocationDecision('granted');setLocationPrompt(false);setStatePicker(true);return}setUf(detected);setLocationPrompt(false);setStatePicker(false);await markLocationDecision('granted');try{await SecureStore.setItemAsync(LOCATION_UF_KEY,detected)}catch{}}catch{setLocationPrompt(false);setStatePicker(true)}finally{setLocationBusy(false)}};
  useEffect(()=>{let active=true;(async()=>{try{const savedUf=await SecureStore.getItemAsync(LOCATION_UF_KEY),decision=await SecureStore.getItemAsync(LOCATION_DECISION_KEY);if(active&&savedUf&&UFS.some(([c])=>c===savedUf))setUf(savedUf);if(active)setLocationDecision(decision||'')}catch{}finally{if(active)setPrefsReady(true)}for(const k of ['PRESIDENTE:BR','GOVERNADOR:MG']){const c=await loadScope(k);if(active&&c)setScopes(prev=>({...prev,[k]:c}))}if(active)refresh('PRESIDENTE','BR')})();return()=>{active=false}},[]);
  useEffect(()=>{if(prefsReady&&category!=='PRESIDENTE'&&!locationDecision)setLocationPrompt(true)},[prefsReady,category,locationDecision]);useEffect(()=>{const sub=AppState.addEventListener('change',next=>{if(appState.current.match(/inactive|background/)&&next==='active')refresh(office,uf);appState.current=next});return()=>sub.remove()},[office,uf]);useEffect(()=>{refresh(office,uf)},[office,uf]);
  const rows=(current.polls||[]).filter(p=>source==='Todas'||p.institute===source),stamp=current.updatedAt?new Date(current.updatedAt):null,stampText=stamp&&!Number.isNaN(stamp.getTime())?stamp.toLocaleString('pt-BR',{hour:'2-digit',minute:'2-digit',day:'2-digit',month:'2-digit'}):'carga local verificada',syncing=syncingKey===currentKey;const leaders=rows.filter(p=>p.results?.length).map(p=>p.results[0][0]),unique=[...new Set(leaders)],summary=leaders.length?(unique.length===1?`${unique[0]} aparece numericamente à frente nos levantamentos exibidos.`:'Os levantamentos exibidos têm resultados diferentes. Compare instituto, data e margem de erro.'):'Ainda não encontrei levantamento registrado e verificável para este filtro.';
  const officeLabel={PRESIDENTE:'Presidente',GOVERNADOR:'Governador',SENADOR:'Senador',DEPUTADO_FEDERAL:'Deputado Federal',DEPUTADO_ESTADUAL:'Deputado Estadual',DEPUTADO_DISTRITAL:'Deputado Distrital'}[office]||office;
  return <><ScrollView contentContainerStyle={[s.content,{paddingBottom:118}]} keyboardShouldPersistTaps="handled"><View style={{flexDirection:'row',alignItems:'flex-start',justifyContent:'space-between',gap:10}}><View style={{flex:1}}><Text style={[s.pageTitle,{fontSize:34,letterSpacing:-1}]}>Pesquisas</Text><Text style={[s.pageSub,{fontSize:13,lineHeight:19}]}>Acompanhe levantamentos eleitorais com fonte, data e metodologia.</Text></View><TouchableOpacity onPress={()=>refresh(office,uf)} disabled={syncing} style={{marginTop:3,width:42,height:42,borderRadius:15,borderWidth:1,borderColor:s._border,backgroundColor:s._surface,alignItems:'center',justifyContent:'center'}}><Text style={{color:s._blue,fontSize:18,fontWeight:'900'}}>↻</Text></TouchableOpacity></View><View style={{flexDirection:'row',alignItems:'center',gap:7,marginTop:-5}}><View style={{width:8,height:8,borderRadius:4,backgroundColor:syncing?'#F0A020':'#20B779'}}/><Text style={{color:s._muted,fontSize:9}}>Última atualização: {stampText}{syncing?' · atualizando…':''}</Text></View>
    <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={{gap:8,paddingVertical:2}}>{[['PRESIDENTE','Presidente'],['GOVERNADOR','Governador'],['SENADOR','Senador'],['DEPUTADOS','Deputados']].map(([k,label])=><TouchableOpacity key={k} onPress={()=>setCategory(k)} style={{paddingVertical:11,paddingHorizontal:15,borderRadius:20,borderWidth:1,borderColor:category===k?s._blue:s._border,backgroundColor:category===k?s._blue:s._surface}}><Text style={{color:category===k?'#fff':s._text,fontSize:10,fontWeight:'900'}}>{label}</Text></TouchableOpacity>)}</ScrollView>
    {category==='DEPUTADOS'?<View style={{flexDirection:'row',gap:8}}><TouchableOpacity onPress={()=>setDeputyKind('FEDERAL')} style={{paddingVertical:9,paddingHorizontal:15,borderRadius:16,borderWidth:1,borderColor:deputyKind==='FEDERAL'?s._blue:s._border,backgroundColor:deputyKind==='FEDERAL'?'rgba(30,126,245,.09)':s._surface}}><Text style={{color:deputyKind==='FEDERAL'?s._blue:s._text,fontSize:9,fontWeight:'900'}}>Federal</Text></TouchableOpacity><TouchableOpacity onPress={()=>setDeputyKind('LOCAL')} style={{paddingVertical:9,paddingHorizontal:15,borderRadius:16,borderWidth:1,borderColor:deputyKind==='LOCAL'?s._blue:s._border,backgroundColor:deputyKind==='LOCAL'?'rgba(30,126,245,.09)':s._surface}}><Text style={{color:deputyKind==='LOCAL'?s._blue:s._text,fontSize:9,fontWeight:'900'}}>{uf==='DF'?'Distrital':'Estadual'}</Text></TouchableOpacity></View>:null}
    {category!=='PRESIDENTE'?<View style={{flexDirection:'row',alignItems:'center',gap:8,flexWrap:'wrap'}}><TouchableOpacity onPress={()=>setStatePicker(true)} style={{height:42,paddingHorizontal:14,borderRadius:15,borderWidth:1,borderColor:s._border,backgroundColor:s._surface,flexDirection:'row',alignItems:'center',gap:7}}><Text style={{color:s._muted,fontSize:8,fontWeight:'900'}}>ESTADO</Text><Text style={{color:s._text,fontSize:13,fontWeight:'900'}}>{uf}</Text><Text style={{color:s._blue,fontSize:11}}>⌄</Text></TouchableOpacity><TouchableOpacity onPress={detectState} disabled={locationBusy} style={{height:42,paddingHorizontal:13,borderRadius:15,borderWidth:1,borderColor:'rgba(30,126,245,.28)',backgroundColor:'rgba(30,126,245,.05)',flexDirection:'row',alignItems:'center',gap:5}}><Text style={{color:s._blue,fontSize:13}}>⌖</Text><Text style={{color:s._blue,fontSize:8,fontWeight:'900'}}>{locationBusy?'LOCALIZANDO…':'MEU ESTADO'}</Text></TouchableOpacity></View>:null}
    <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={{gap:8,paddingVertical:1}}>{['Todas','Datafolha','Quaest'].map(x=><TouchableOpacity key={x} onPress={()=>setSource(x)} style={{paddingVertical:9,paddingHorizontal:16,borderRadius:18,borderWidth:1,borderColor:source===x?s._blue:s._border,backgroundColor:source===x?s._blue:s._surface}}><Text style={{color:source===x?'#fff':s._text,fontSize:9,fontWeight:'900'}}>{x}</Text></TouchableOpacity>)}</ScrollView>
    <View style={{borderRadius:20,borderWidth:1,borderColor:'rgba(30,126,245,.24)',backgroundColor:'rgba(30,126,245,.04)',padding:14}}><View style={{flexDirection:'row',alignItems:'center',gap:12}}><View style={{width:86,alignItems:'center'}}><XisOfficial height={88}/></View><View style={{flex:1}}><Text style={{color:s._text,fontWeight:'900',fontSize:18}}>Resumo do Xis</Text><Text style={{color:s._muted,fontSize:10,lineHeight:16,marginTop:5}}>{summary}</Text></View></View></View>
    {rows.length?<>{source==='Todas'?<PollComparison polls={rows} office={office} uf={uf}/>:null}<View style={{gap:11}}>{rows.map(p=><PollCard key={p.id} poll={p}/>)}</View></>:<View style={{backgroundColor:s._surface,borderWidth:1,borderColor:s._border,borderRadius:20,padding:18}}><Text style={{color:s._text,fontSize:18,fontWeight:'900'}}>{syncing?'Buscando pesquisas…':'Nenhuma pesquisa verificável encontrada'}</Text><Text style={{color:s._muted,fontSize:10,lineHeight:16,marginTop:6}}>{syncing?'Consultando as fontes agora.':`Não encontramos levantamento publicado e verificável para ${officeLabel}${office==='PRESIDENTE'?'':` · ${uf}`}. Quando houver, aparecerá automaticamente.`}</Text></View>}
    <TouchableOpacity style={[s.secondary,{borderRadius:16}]} onPress={()=>Linking.openURL(TSE_POLLS)}><Text style={s.secondaryText}>ABRIR PESQUISAS NO TSE</Text></TouchableOpacity><Text style={{color:s._muted,fontSize:8,lineHeight:13,textAlign:'center'}}>Pesquisa é um retrato do momento, não previsão do resultado. Em deputados, preservamos o tipo original do levantamento.</Text></ScrollView>
    <Modal visible={locationPrompt} transparent animationType="fade" onRequestClose={()=>setLocationPrompt(false)}><SafeAreaView style={{flex:1,backgroundColor:'rgba(1,12,29,.72)',justifyContent:'center',padding:22}}><View style={{backgroundColor:s._surface,borderRadius:24,padding:20,borderWidth:1,borderColor:s._border}}><View style={{width:52,height:52,borderRadius:17,backgroundColor:'rgba(30,126,245,.09)',alignItems:'center',justifyContent:'center',alignSelf:'center'}}><Text style={{color:s._blue,fontSize:25}}>⌖</Text></View><Text style={{color:s._text,fontSize:21,fontWeight:'900',textAlign:'center',marginTop:12}}>Pesquisas do seu estado</Text><Text style={{color:s._muted,fontSize:11,lineHeight:17,textAlign:'center',marginTop:8}}>Posso usar sua localização aproximada para selecionar automaticamente a UF?</Text><View style={{marginTop:12,padding:11,borderRadius:13,backgroundColor:s._surface2}}><Text style={{color:s._text,fontSize:9,lineHeight:14,textAlign:'center'}}>Usamos a localização somente para descobrir o estado. As coordenadas não são enviadas ao servidor nem ficam salvas.</Text></View><TouchableOpacity disabled={locationBusy} onPress={detectState} style={{marginTop:15,height:48,borderRadius:15,backgroundColor:s._blue,alignItems:'center',justifyContent:'center'}}><Text style={{color:'#fff',fontSize:10,fontWeight:'900'}}>{locationBusy?'LOCALIZANDO…':'USAR MEU ESTADO'}</Text></TouchableOpacity><TouchableOpacity onPress={()=>{setLocationPrompt(false);setStatePicker(true)}} style={{marginTop:9,height:46,borderRadius:15,borderWidth:1,borderColor:s._border,alignItems:'center',justifyContent:'center'}}><Text style={{color:s._text,fontSize:10,fontWeight:'900'}}>ESCOLHER ESTADO</Text></TouchableOpacity><TouchableOpacity onPress={async()=>{setLocationPrompt(false);await markLocationDecision('denied')}} style={{alignItems:'center',paddingVertical:12}}><Text style={{color:s._muted,fontSize:10}}>Agora não</Text></TouchableOpacity></View></SafeAreaView></Modal>
    <Modal visible={statePicker} transparent animationType="slide" onRequestClose={()=>setStatePicker(false)}><SafeAreaView style={{flex:1,backgroundColor:'rgba(1,12,29,.66)',justifyContent:'flex-end'}}><View style={{maxHeight:'76%',backgroundColor:s._surface,borderTopLeftRadius:26,borderTopRightRadius:26,padding:18}}><View style={{flexDirection:'row',justifyContent:'space-between',alignItems:'center',marginBottom:12}}><View><Text style={{color:s._text,fontSize:20,fontWeight:'900'}}>Escolha o estado</Text><Text style={{color:s._muted,fontSize:9,marginTop:2}}>Você pode trocar quando quiser.</Text></View><TouchableOpacity onPress={()=>setStatePicker(false)} style={{width:36,height:36,borderRadius:18,backgroundColor:s._surface2,alignItems:'center',justifyContent:'center'}}><Text style={{color:s._text,fontSize:19}}>×</Text></TouchableOpacity></View><ScrollView contentContainerStyle={{flexDirection:'row',flexWrap:'wrap',gap:8,paddingBottom:24}}>{UFS.map(([code,name])=><TouchableOpacity key={code} onPress={()=>selectUf(code)} style={{width:'31%',minHeight:58,borderRadius:14,borderWidth:1,borderColor:uf===code?s._blue:s._border,backgroundColor:uf===code?'rgba(30,126,245,.09)':s._surface2,padding:9,justifyContent:'center'}}><Text style={{color:uf===code?s._blue:s._text,fontSize:13,fontWeight:'900'}}>{code}</Text><Text style={{color:s._muted,fontSize:8,marginTop:2}} numberOfLines={2}>{name}</Text></TouchableOpacity>)}</ScrollView></View></SafeAreaView></Modal></>
}'''
text=replace_between(text,'function PollsScreen(){','\nfunction ResultsScreen(){',polls_screen,'PollsScreen')

results=r'''function ResultsScreen(){
  const s=useStyles();const {matchesName}=useFavorites();const [office,setOffice]=useState('PRESIDENTE'),[uf,setUf]=useState('MG'),[data,setData]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState('');const timer=useRef(null),app=useRef(AppState.currentState);
  const load=async()=>{if(busy)return;setBusy(true);try{const r=await fetch(`${LIVE_RESULTS_API}?office=${encodeURIComponent(office)}&uf=${encodeURIComponent(office==='PRESIDENTE'?'BR':uf)}&t=${Date.now()}`,{headers:{Accept:'application/json','Cache-Control':'no-cache'}});const j=await r.json().catch(()=>null);if(r.ok&&j?.ok){setData(j);setError('')}else throw new Error('SOURCE')}catch{setError('Não consegui consultar a fonte oficial agora.')}finally{setBusy(false)}};
  useEffect(()=>{load()},[office,uf]);useEffect(()=>{if(timer.current)clearInterval(timer.current);timer.current=null;if(data?.active)timer.current=setInterval(load,20000);return()=>{if(timer.current)clearInterval(timer.current)}},[data?.active,office,uf]);useEffect(()=>{const sub=AppState.addEventListener('change',next=>{if(app.current.match(/inactive|background/)&&next==='active')load();app.current=next});return()=>sub.remove()},[office,uf]);
  const rows=data?.candidates||[],pct=Number(data?.totals?.percentSections||0),live=Boolean(data?.active),scopeUf=office==='PRESIDENTE'?'BR':uf;
  return <ScrollView contentContainerStyle={[s.content,{paddingBottom:118}]}><View style={{flexDirection:'row',justifyContent:'space-between',alignItems:'flex-start',gap:10}}><View style={{flex:1}}><Text style={[s.pageTitle,{fontSize:34}]}>Apuração</Text><Text style={s.pageSub}>Resultados oficiais do TSE em uma tela preparada para acompanhar a totalização em tempo real.</Text></View><View style={{paddingHorizontal:10,paddingVertical:7,borderRadius:13,backgroundColor:live?'rgba(27,185,110,.12)':'rgba(240,160,32,.12)',borderWidth:1,borderColor:live?'#1BB96E':'#F0A020'}}><Text style={{color:live?'#1BB96E':'#F0A020',fontSize:9,fontWeight:'900'}}>{live?'● AO VIVO':'○ AGUARDANDO'}</Text></View></View>
    <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={{gap:8}}>{[['PRESIDENTE','Presidente'],['GOVERNADOR','Governador'],['SENADOR','Senador'],['DEPUTADO_FEDERAL','Dep. Federal'],[uf==='DF'?'DEPUTADO_DISTRITAL':'DEPUTADO_ESTADUAL',uf==='DF'?'Dep. Distrital':'Dep. Estadual']].map(([k,l])=><TouchableOpacity key={k} onPress={()=>setOffice(k)} style={{paddingVertical:10,paddingHorizontal:14,borderRadius:18,borderWidth:1,borderColor:office===k?s._blue:s._border,backgroundColor:office===k?s._blue:s._surface}}><Text style={{color:office===k?'#fff':s._text,fontSize:9,fontWeight:'900'}}>{l}</Text></TouchableOpacity>)}</ScrollView>
    {office!=='PRESIDENTE'?<View style={{flexDirection:'row',alignItems:'center',gap:8}}><Text style={{color:s._muted,fontSize:9,fontWeight:'900'}}>UF</Text><TextInput value={uf} onChangeText={v=>setUf(v.toUpperCase().replace(/[^A-Z]/g,'').slice(0,2))} maxLength={2} placeholder="MG" placeholderTextColor={s._muted} style={[s.input,{width:82,height:42,marginBottom:0,textAlign:'center',fontWeight:'900'}]}/></View>:null}
    <View style={{backgroundColor:s._surface,borderWidth:1,borderColor:s._border,borderRadius:20,padding:17}}><View style={{flexDirection:'row',justifyContent:'space-between',alignItems:'center'}}><View><Text style={{color:s._muted,fontSize:8,fontWeight:'900'}}>SEÇÕES TOTALIZADAS</Text><Text style={{color:s._text,fontSize:32,fontWeight:'900',marginTop:3}}>{live?`${pct.toFixed(2).replace('.',',')}%`:'—'}</Text></View><TouchableOpacity onPress={load} disabled={busy} style={{width:42,height:42,borderRadius:14,borderWidth:1,borderColor:s._border,alignItems:'center',justifyContent:'center'}}><Text style={{color:s._blue,fontSize:18}}>↻</Text></TouchableOpacity></View><View style={{height:9,borderRadius:5,backgroundColor:s._surface2,overflow:'hidden',marginTop:11}}><View style={{height:'100%',width:`${Math.max(0,Math.min(100,pct))}%`,backgroundColor:s._blue,borderRadius:5}}/></View><Text style={{color:s._muted,fontSize:9,lineHeight:14,marginTop:9}}>{data?.message||error||'Consultando se a apuração de 2026 já começou.'}</Text>{data?.tseUpdatedAt?<Text style={{color:s._muted,fontSize:8,marginTop:4}}>TSE: {data.tseUpdatedAt}</Text>:null}</View>
    {live&&rows.length?<View style={{gap:9}}>{rows.slice(0,50).map((c,i)=>{const fav=matchesName(c.name,office,scopeUf);return <View key={`${c.number}-${c.name}`} style={{backgroundColor:fav?'rgba(240,160,0,.07)':s._surface,borderWidth:1,borderColor:fav?'rgba(240,160,0,.42)':s._border,borderRadius:17,padding:13}}><View style={{flexDirection:'row',alignItems:'center',gap:10}}><Text style={{color:fav?'#C98000':s._muted,fontSize:11,fontWeight:'900',width:26}}>{fav?'★':`${i+1}º`}</Text><View style={{flex:1}}><Text style={{color:s._text,fontSize:14,fontWeight:'900'}} numberOfLines={1}>{c.name}</Text><Text style={{color:s._muted,fontSize:8,marginTop:2}}>{c.number}{c.party?` · ${c.party}`:''}{fav?' · FAVORITO':''}</Text></View><View style={{alignItems:'flex-end'}}><Text style={{color:fav?'#C98000':s._blue,fontSize:17,fontWeight:'900'}}>{Number(c.percent||0).toFixed(2).replace('.',',')}%</Text><Text style={{color:s._muted,fontSize:8}}>{Number(c.votes||0).toLocaleString('pt-BR')} votos</Text></View></View></View>})}</View>:<View style={{borderRadius:20,borderWidth:1,borderColor:'rgba(30,126,245,.20)',backgroundColor:'rgba(30,126,245,.035)',padding:18,alignItems:'center'}}><View style={{width:54,height:54,borderRadius:18,backgroundColor:'rgba(30,126,245,.09)',alignItems:'center',justifyContent:'center'}}><Text style={{color:s._blue,fontSize:25}}>◉</Text></View><Text style={{color:s._text,fontSize:18,fontWeight:'900',marginTop:10}}>Tudo pronto para a apuração</Text><Text style={{color:s._muted,fontSize:10,lineHeight:16,textAlign:'center',marginTop:6}}>Antes do TSE iniciar a totalização, não exibimos números fictícios. Assim que houver votos oficiais, esta tela entra em AO VIVO e atualiza a cada 20 segundos enquanto estiver aberta.</Text></View>}
    <Text style={{color:s._muted,fontSize:8,lineHeight:13,textAlign:'center'}}>Fonte da apuração: Tribunal Superior Eleitoral (TSE).</Text></ScrollView>
}'''
text=replace_between(text,'function ResultsScreen(){','\nfunction Settings({onLogout})',results,'ResultsScreen')

# Version bump.
text=replace_once(text,"const VERSION='0.3.33';","const VERSION='0.3.34';",'visible version')
text=replace_once(text,"const APP_VERSION='0.3.33';","const APP_VERSION='0.3.34';",'embedded auth version') if "const APP_VERSION='0.3.33';" in text else text
p.write_text(text,encoding='utf-8')

# Separate version files.
a=Path('AuthGateV020.js');at=a.read_text(encoding='utf-8');at=replace_once(at,"const APP_VERSION='0.3.33';","const APP_VERSION='0.3.34';",'AuthGate version');a.write_text(at,encoding='utf-8')
x=Path('XisEngine.js');xt=x.read_text(encoding='utf-8');xt=replace_once(xt,"'X-App-Version':'0.3.33'","'X-App-Version':'0.3.34'",'Xis header version');x.write_text(xt,encoding='utf-8')
app_path=Path('app.json');app=json.loads(app_path.read_text(encoding='utf-8'));app['expo']['version']='0.3.34';app['expo']['android']['versionCode']=38;app['expo'].setdefault('extra',{})['release']='pesquisas-apuracao-ui-v034';app_path.write_text(json.dumps(app,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
pkg_path=Path('package.json');pkg=json.loads(pkg_path.read_text(encoding='utf-8'));pkg['version']='0.3.34';pkg_path.write_text(json.dumps(pkg,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
print('RAIO-X v0.3.34: Apuracao bottom tab + repaired Pesquisas UI + fixed location modals applied')
