import patch_v032_location
from pathlib import Path
import json


def replace_once(path, old, new, label):
    p=Path(path); text=p.read_text(encoding='utf-8')
    if old not in text: raise SystemExit(f'Missing v0.3.33 target: {label} in {path}')
    p.write_text(text.replace(old,new,1),encoding='utf-8')

p=Path('AppV020.js'); text=p.read_text(encoding='utf-8')

# Live results API constant.
marker="const LIVE_POLLS_API='https://raiox-xis-ai.vercel.app/api/polls';"
if marker not in text: raise SystemExit('Missing LIVE_POLLS_API')
text=text.replace(marker,marker+"\nconst LIVE_RESULTS_API='https://raiox-xis-ai.vercel.app/api/results';",1)

# Poll card labels for all offices and methodology display.
start=text.find('function PollCard({poll})')
end=text.find('\nfunction PollComparison(',start)
if start<0 or end<0: raise SystemExit('Missing PollCard')
pollcard=r'''function PollCard({poll}){
  const s=useStyles();const badge=(poll.institute||'?').slice(0,1).toUpperCase();const purple=poll.institute==='Quaest';
  const labels={PRESIDENTE:'Presidente · 1º turno',GOVERNADOR:`Governador · ${poll.uf}`,SENADOR:`Senador · ${poll.uf}`,DEPUTADO_FEDERAL:`Deputado Federal · ${poll.uf}`,DEPUTADO_ESTADUAL:`Deputado Estadual · ${poll.uf}`,DEPUTADO_DISTRITAL:'Deputado Distrital · DF'};
  const officeLabel=labels[poll.office]||poll.office||'Pesquisa eleitoral';
  return <View style={{backgroundColor:s._surface,borderWidth:1,borderColor:s._border,borderRadius:22,padding:16,shadowColor:'#00152F',shadowOpacity:.06,shadowRadius:14,shadowOffset:{width:0,height:5},elevation:2}}>
    <View style={{flexDirection:'row',alignItems:'center',justifyContent:'space-between',gap:8}}><View style={{flexDirection:'row',alignItems:'center',gap:9,flex:1}}><View style={{width:36,height:36,borderRadius:18,backgroundColor:purple?'#6F2DBD':s._blue,alignItems:'center',justifyContent:'center'}}><Text style={{color:'#fff',fontSize:18,fontWeight:'900'}}>{badge}</Text></View><View style={{flex:1}}><Text style={{color:s._text,fontSize:18,fontWeight:'900'}}>{poll.institute}</Text><Text style={{color:s._muted,fontSize:9,marginTop:1}}>{officeLabel}</Text></View></View><Text style={{color:s._blue,fontSize:9,fontWeight:'900'}}>{poll.published}</Text></View>
    <View style={{marginTop:13,paddingVertical:10,borderTopWidth:1,borderBottomWidth:1,borderColor:s._border}}>{poll.mode?<Text style={{color:s._blue,fontSize:9,fontWeight:'900',lineHeight:15}}>TIPO: {poll.mode.toUpperCase()}</Text>:null}{poll.question?<Text style={{color:s._text,fontSize:9,lineHeight:14,marginBottom:3}}>{poll.question}</Text>:null}<Text style={{color:s._muted,fontSize:9,lineHeight:15}}>▣ Campo: {poll.field}</Text><Text style={{color:s._muted,fontSize:9,lineHeight:15}}>♟ Amostra: {Number(poll.sample||0).toLocaleString('pt-BR')}     ◉ Margem: ±{poll.margin} p.p.</Text><Text style={{color:s._muted,fontSize:9,lineHeight:15}}>▤ Registro TSE: {poll.registry}</Text></View>
    <View style={{marginTop:2}}>{(poll.results||[]).map(([n,p,v],i)=><PollBar key={`${poll.id}-${n}`} name={n} party={p} pct={v} leader={i===0}/>)}</View>
    {poll.sourceUrl?<TouchableOpacity onPress={()=>Linking.openURL(poll.sourceUrl)} style={{marginTop:14,paddingTop:11,borderTopWidth:1,borderTopColor:s._border,alignItems:'center'}}><Text style={{color:s._text,fontSize:10,fontWeight:'800'}}>Ver detalhes   ›</Text></TouchableOpacity>:null}
  </View>
}'''
text=text[:start]+pollcard+text[end:]

# Complete research screen: President, Governor, Senate, Federal/State/District deputies.
start=text.find('function PollsScreen(){')
end=text.find('\nfunction Settings({onLogout})',start)
if start<0 or end<0: raise SystemExit('Missing PollsScreen')
screen=r'''function PollsScreen(){
  const s=useStyles();
  const [category,setCategory]=useState('PRESIDENTE'),[deputyKind,setDeputyKind]=useState('FEDERAL'),[uf,setUf]=useState('MG'),[source,setSource]=useState('Todas');
  const [locationPrompt,setLocationPrompt]=useState(false),[statePicker,setStatePicker]=useState(false),[locationBusy,setLocationBusy]=useState(false),[prefsReady,setPrefsReady]=useState(false),[locationDecision,setLocationDecision]=useState('');
  const UFS=[['AC','Acre'],['AL','Alagoas'],['AP','Amapá'],['AM','Amazonas'],['BA','Bahia'],['CE','Ceará'],['DF','Distrito Federal'],['ES','Espírito Santo'],['GO','Goiás'],['MA','Maranhão'],['MT','Mato Grosso'],['MS','Mato Grosso do Sul'],['MG','Minas Gerais'],['PA','Pará'],['PB','Paraíba'],['PR','Paraná'],['PE','Pernambuco'],['PI','Piauí'],['RJ','Rio de Janeiro'],['RN','Rio Grande do Norte'],['RS','Rio Grande do Sul'],['RO','Rondônia'],['RR','Roraima'],['SC','Santa Catarina'],['SP','São Paulo'],['SE','Sergipe'],['TO','Tocantins']];
  const UF_BY_NAME=Object.fromEntries(UFS.map(([code,name])=>[normalize(name),code]));
  const LOCATION_UF_KEY='raiox.polls.uf.v032',LOCATION_DECISION_KEY='raiox.polls.location.decision.v032';
  const MG_BOOTSTRAP=[{id:'df-mg-gov-2108',institute:'Datafolha',office:'GOVERNADOR',uf:'MG',published:'21/08/2026',field:'18 a 20/08/2026',sample:1204,margin:3,registry:'MG-00446/2026',sourceUrl:'https://www1.folha.uol.com.br/poder/2026/08/datafolha-cleitinho-lidera-disputa-em-mg-com-32-patrus-e-kalil-tem-12-cada.shtml',mode:'Estimulada',question:'Governador de Minas Gerais - 1º turno',results:[['Cleitinho Azevedo','Republicanos',32],['Patrus Ananias','PT',12],['Alexandre Kalil','PDT',12],['Mateus Simões','PSD',4],['Flávio Roscoe','PL',4],['Gabriel Azevedo','MDB',4],['Branco/Nulo','',14],['Indecisos','',13]]}];
  const initialScopes={'PRESIDENTE:BR':{polls:POLL_SNAPSHOT,updatedAt:null,note:''},'GOVERNADOR:MG':{polls:MG_BOOTSTRAP,updatedAt:null,note:'Última carga verificada; buscando atualização'}};
  const [scopes,setScopes]=useState(initialScopes),[syncingKey,setSyncingKey]=useState('');
  const appState=useRef(AppState.currentState),inFlight=useRef(new Set());
  const office=category==='DEPUTADOS'?(deputyKind==='FEDERAL'?'DEPUTADO_FEDERAL':uf==='DF'?'DEPUTADO_DISTRITAL':'DEPUTADO_ESTADUAL'):category;
  const scopeKey=(o=office,u=uf)=>o==='PRESIDENTE'?'PRESIDENTE:BR':`${o}:${String(u||'MG').toUpperCase().slice(0,2)}`;
  const cacheKey=k=>`${POLLS_CACHE_KEY}.${k}`,currentKey=scopeKey(),current=scopes[currentKey]||{polls:[],updatedAt:null,note:''};
  const saveScope=async(k,value)=>{try{await SecureStore.setItemAsync(cacheKey(k),JSON.stringify(value))}catch{}};
  const loadScope=async(k)=>{try{const raw=await SecureStore.getItemAsync(cacheKey(k));if(!raw)return null;const v=JSON.parse(raw);return Array.isArray(v?.polls)&&v.polls.length?v:null}catch{return null}};
  const setScope=async(k,polls,at,note)=>{if(!Array.isArray(polls)||!polls.length)return false;const value={polls,updatedAt:at||new Date().toISOString(),note:note||''};setScopes(prev=>({...prev,[k]:value}));await saveScope(k,value);return true};
  const refresh=async(nextOffice=office,nextUf=uf)=>{const o=nextOffice||'PRESIDENTE',u=o==='PRESIDENTE'?'BR':String(nextUf||'MG').toUpperCase().slice(0,2),k=scopeKey(o,u);if(inFlight.current.has(k))return;inFlight.current.add(k);setSyncingKey(k);setScopes(prev=>({...prev,[k]:{...(prev[k]||{polls:[],updatedAt:null}),note:'Atualizando…'}}));try{const response=await fetch(`${LIVE_POLLS_API}?office=${encodeURIComponent(o)}&uf=${encodeURIComponent(u)}&t=${Date.now()}`,{headers:{Accept:'application/json','Cache-Control':'no-cache'}});const data=await response.json().catch(()=>null);if(response.ok&&data?.ok&&Array.isArray(data.polls)&&data.polls.length){await setScope(k,data.polls,data.fetchedAt,data.fresh?'Atualizado agora':'Sem pesquisa nova; última carga válida mantida');return}setScopes(prev=>({...prev,[k]:{...(prev[k]||{polls:[],updatedAt:null}),updatedAt:data?.fetchedAt||prev[k]?.updatedAt||null,note:data?.warning||'Nenhuma pesquisa registrada e verificável encontrada.'}}))}catch{const cached=await loadScope(k);if(cached)setScopes(prev=>({...prev,[k]:{...cached,note:'Sem conexão; última carga válida mantida'}}));else setScopes(prev=>({...prev,[k]:{...(prev[k]||{polls:[],updatedAt:null}),note:'Sem conexão com as fontes'}}))}finally{inFlight.current.delete(k);setSyncingKey(v=>v===k?'':v)}};
  const markLocationDecision=async value=>{setLocationDecision(value);try{await SecureStore.setItemAsync(LOCATION_DECISION_KEY,value)}catch{}};
  const selectUf=async code=>{if(!UFS.some(([c])=>c===code))return;setUf(code);setStatePicker(false);setLocationPrompt(false);await markLocationDecision('manual');try{await SecureStore.setItemAsync(LOCATION_UF_KEY,code)}catch{}};
  const detectState=async()=>{if(locationBusy)return;setLocationBusy(true);try{const permission=await Location.requestForegroundPermissionsAsync();if(permission.status!=='granted'){await markLocationDecision('denied');setLocationPrompt(false);setStatePicker(true);return}const pos=await Location.getCurrentPositionAsync({accuracy:Location.Accuracy.Low});const places=await Location.reverseGeocodeAsync({latitude:pos.coords.latitude,longitude:pos.coords.longitude});const place=places?.[0]||{},country=normalize(place.isoCountryCode||place.country||'');let region=normalize(place.region||place.subregion||'').replace(/^ESTADO DE /,'').replace(/^STATE OF /,'');const detected=UF_BY_NAME[region]||(UFS.some(([c])=>c===region)?region:'');if(!detected||!(country==='BR'||country==='BRA'||country==='BRASIL'||country==='BRAZIL')){await markLocationDecision('granted');setLocationPrompt(false);setStatePicker(true);return}setUf(detected);setLocationPrompt(false);setStatePicker(false);await markLocationDecision('granted');try{await SecureStore.setItemAsync(LOCATION_UF_KEY,detected)}catch{}}catch{setLocationPrompt(false);setStatePicker(true)}finally{setLocationBusy(false)}};
  useEffect(()=>{let active=true;(async()=>{try{const savedUf=await SecureStore.getItemAsync(LOCATION_UF_KEY),decision=await SecureStore.getItemAsync(LOCATION_DECISION_KEY);if(active&&savedUf&&UFS.some(([c])=>c===savedUf))setUf(savedUf);if(active)setLocationDecision(decision||'')}catch{}finally{if(active)setPrefsReady(true)}for(const k of ['PRESIDENTE:BR','GOVERNADOR:MG']){const c=await loadScope(k);if(active&&c)setScopes(prev=>({...prev,[k]:c}))}if(active)refresh('PRESIDENTE','BR')})();return()=>{active=false}},[]);
  useEffect(()=>{if(prefsReady&&category!=='PRESIDENTE'&&!locationDecision)setLocationPrompt(true)},[prefsReady,category,locationDecision]);
  useEffect(()=>{const sub=AppState.addEventListener('change',next=>{if(appState.current.match(/inactive|background/)&&next==='active')refresh(office,uf);appState.current=next});return()=>sub.remove()},[office,uf]);
  useEffect(()=>{refresh(office,uf)},[office,uf]);
  const rows=(current.polls||[]).filter(p=>source==='Todas'||p.institute===source),stamp=current.updatedAt?new Date(current.updatedAt):null,stampText=stamp&&!Number.isNaN(stamp.getTime())?stamp.toLocaleString('pt-BR',{hour:'2-digit',minute:'2-digit',day:'2-digit',month:'2-digit'}):'carga local verificada',syncing=syncingKey===currentKey;
  const leaders=rows.filter(p=>p.results?.length).map(p=>p.results[0][0]),unique=[...new Set(leaders)],summary=leaders.length?(unique.length===1?`${unique[0]} aparece numericamente à frente nos levantamentos exibidos.`:'Os levantamentos exibidos têm resultados diferentes; confira metodologia, instituto e data.'):'Ainda não encontrei levantamento registrado e verificável para este filtro.';
  return <ScrollView contentContainerStyle={[s.content,{paddingBottom:118}]} keyboardShouldPersistTaps="handled">
    <View style={{flexDirection:'row',alignItems:'flex-start',justifyContent:'space-between',gap:10}}><View style={{flex:1}}><Text style={[s.pageTitle,{fontSize:34,letterSpacing:-1}]}>Pesquisas</Text><Text style={[s.pageSub,{fontSize:13,lineHeight:19}]}>Presidente, governos estaduais, Senado e levantamentos legislativos publicados.</Text></View><TouchableOpacity onPress={()=>refresh(office,uf)} disabled={syncing} style={{marginTop:4,paddingHorizontal:11,paddingVertical:9,borderRadius:14,borderWidth:1,borderColor:s._border,backgroundColor:s._surface}}><Text style={{color:s._blue,fontSize:9,fontWeight:'900'}}>{syncing?'ATUALIZANDO…':'↻ ATUALIZAR'}</Text></TouchableOpacity></View>
    <View style={{flexDirection:'row',alignItems:'center',gap:7,marginTop:-3}}><View style={{width:8,height:8,borderRadius:4,backgroundColor:syncing?'#F0A020':'#20B779'}}/><Text style={{color:s._muted,fontSize:9}}>Última atualização: {stampText}</Text></View>{current.note?<Text style={{color:s._muted,fontSize:8,marginTop:-7}}>{current.note}</Text>:null}
    <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={{gap:8,paddingVertical:2}}>{[['PRESIDENTE','Presidente'],['GOVERNADOR','Governador'],['SENADOR','Senador'],['DEPUTADOS','Deputados']].map(([k,label])=><TouchableOpacity key={k} onPress={()=>setCategory(k)} style={{paddingVertical:11,paddingHorizontal:15,borderRadius:21,borderWidth:1,borderColor:category===k?s._blue:s._border,backgroundColor:category===k?s._blue:s._surface}}><Text style={{color:category===k?'#fff':s._text,fontSize:10,fontWeight:'900'}}>{label}</Text></TouchableOpacity>)}</ScrollView>
    {category==='DEPUTADOS'?<View style={{flexDirection:'row',gap:8}}><TouchableOpacity onPress={()=>setDeputyKind('FEDERAL')} style={{paddingVertical:9,paddingHorizontal:14,borderRadius:16,borderWidth:1,borderColor:deputyKind==='FEDERAL'?s._blue:s._border,backgroundColor:deputyKind==='FEDERAL'?'rgba(30,126,245,.10)':s._surface}}><Text style={{color:deputyKind==='FEDERAL'?s._blue:s._text,fontSize:9,fontWeight:'900'}}>Federal</Text></TouchableOpacity><TouchableOpacity onPress={()=>setDeputyKind('LOCAL')} style={{paddingVertical:9,paddingHorizontal:14,borderRadius:16,borderWidth:1,borderColor:deputyKind==='LOCAL'?s._blue:s._border,backgroundColor:deputyKind==='LOCAL'?'rgba(30,126,245,.10)':s._surface}}><Text style={{color:deputyKind==='LOCAL'?s._blue:s._text,fontSize:9,fontWeight:'900'}}>{uf==='DF'?'Distrital':'Estadual'}</Text></TouchableOpacity></View>:null}
    {category!=='PRESIDENTE'?<View style={{flexDirection:'row',alignItems:'center',gap:8,flexWrap:'wrap'}}><TouchableOpacity onPress={()=>setStatePicker(true)} style={{height:42,paddingHorizontal:14,borderRadius:15,borderWidth:1,borderColor:s._border,backgroundColor:s._surface,flexDirection:'row',alignItems:'center',gap:7}}><Text style={{color:s._muted,fontSize:9,fontWeight:'800'}}>ESTADO</Text><Text style={{color:s._text,fontSize:13,fontWeight:'900'}}>{uf}</Text><Text style={{color:s._blue,fontSize:12}}>⌄</Text></TouchableOpacity><TouchableOpacity onPress={detectState} disabled={locationBusy} style={{height:42,paddingHorizontal:13,borderRadius:15,borderWidth:1,borderColor:'rgba(30,126,245,.28)',backgroundColor:'rgba(30,126,245,.06)',flexDirection:'row',alignItems:'center',gap:6}}><Text style={{color:s._blue,fontSize:14}}>⌖</Text><Text style={{color:s._blue,fontSize:9,fontWeight:'900'}}>{locationBusy?'LOCALIZANDO…':'MEU ESTADO'}</Text></TouchableOpacity></View>:null}
    <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={{gap:8,paddingVertical:1}}>{['Todas','Datafolha','Quaest'].map(x=><TouchableOpacity key={x} style={{paddingVertical:9,paddingHorizontal:15,borderRadius:18,borderWidth:1,borderColor:source===x?s._blue:s._border,backgroundColor:source===x?s._blue:s._surface}} onPress={()=>setSource(x)}><Text style={{color:source===x?'#fff':s._text,fontSize:9,fontWeight:'900'}}>{x}</Text></TouchableOpacity>)}</ScrollView>
    <View style={{borderRadius:22,borderWidth:1,borderColor:'rgba(30,126,245,.28)',backgroundColor:'rgba(30,126,245,.045)',overflow:'hidden',padding:14}}><View style={{flexDirection:'row',alignItems:'center',gap:13}}><View style={{width:110,alignItems:'center'}}><XisOfficial height={112}/></View><View style={{flex:1}}><Text style={{color:s._text,fontWeight:'900',fontSize:19}}>Resumo do Xis</Text><Text style={{color:s._muted,fontSize:11,lineHeight:17,marginTop:7}}>{summary}</Text></View></View></View>
    {rows.length?<><View style={{gap:12}}>{rows.map(p=><PollCard key={p.id} poll={p}/>)}</View></>:<View style={{backgroundColor:s._surface,borderWidth:1,borderColor:s._border,borderRadius:22,padding:18}}><Text style={{color:s._text,fontSize:18,fontWeight:'900'}}>{syncing?'Buscando pesquisas…':'Nenhuma pesquisa verificável encontrada'}</Text><Text style={{color:s._muted,fontSize:11,lineHeight:17,marginTop:7}}>{syncing?'Consultando as fontes agora.':'Para esse cargo e UF, o app não cria ranking. Quando houver levantamento publicado e registrado, ele aparecerá aqui automaticamente.'}</Text></View>}
    <TouchableOpacity style={[s.secondary,{borderRadius:17}]} onPress={()=>Linking.openURL(TSE_POLLS)}><Text style={s.secondaryText}>ABRIR PESQUISAS ELEITORAIS NO TSE</Text></TouchableOpacity>
    <Text style={{color:s._muted,fontSize:8,lineHeight:13,textAlign:'center'}}>Pesquisas são retratos do momento. Em deputados, o tipo de levantamento (espontâneo, estimulado ou regional) é preservado.</Text>
    <Modal visible={locationPrompt} transparent animationType="fade" onRequestClose={()=>setLocationPrompt(false)}><View style={{flex:1,backgroundColor:'rgba(1,12,29,.72)',justifyContent:'center',padding:20}}><View style={{backgroundColor:s._surface,borderRadius:26,padding:20,borderWidth:1,borderColor:s._border,alignItems:'center'}}><XisOfficial height={126}/><Text style={{color:s._text,fontSize:22,fontWeight:'900',textAlign:'center'}}>Pesquisas do seu estado</Text><Text style={{color:s._muted,fontSize:12,lineHeight:18,textAlign:'center',marginTop:9}}>Posso usar sua localização aproximada para selecionar automaticamente a UF?</Text><Text style={{color:s._text,fontSize:10,fontWeight:'800',textAlign:'center',marginTop:12}}>Usamos a localização apenas para descobrir a UF. As coordenadas não são enviadas ao servidor nem ficam salvas.</Text><TouchableOpacity disabled={locationBusy} onPress={detectState} style={{width:'100%',marginTop:16,paddingVertical:14,borderRadius:16,backgroundColor:s._blue,alignItems:'center'}}><Text style={{color:'#fff',fontSize:11,fontWeight:'900'}}>USAR MEU ESTADO</Text></TouchableOpacity><TouchableOpacity onPress={()=>{setLocationPrompt(false);setStatePicker(true)}} style={{width:'100%',marginTop:9,paddingVertical:13,borderRadius:16,borderWidth:1,borderColor:s._border,alignItems:'center'}}><Text style={{color:s._text,fontSize:10,fontWeight:'900'}}>ESCOLHER ESTADO</Text></TouchableOpacity><TouchableOpacity onPress={async()=>{setLocationPrompt(false);await markLocationDecision('denied')}} style={{paddingVertical:12}}><Text style={{color:s._muted,fontSize:10}}>Agora não</Text></TouchableOpacity></View></View></Modal>
    <Modal visible={statePicker} transparent animationType="slide" onRequestClose={()=>setStatePicker(false)}><View style={{flex:1,backgroundColor:'rgba(1,12,29,.66)',justifyContent:'flex-end'}}><View style={{maxHeight:'78%',backgroundColor:s._surface,borderTopLeftRadius:28,borderTopRightRadius:28,padding:18}}><Text style={{color:s._text,fontSize:20,fontWeight:'900',marginBottom:12}}>Escolha o estado</Text><ScrollView contentContainerStyle={{flexDirection:'row',flexWrap:'wrap',gap:8,paddingBottom:24}}>{UFS.map(([code,name])=><TouchableOpacity key={code} onPress={()=>selectUf(code)} style={{width:'31%',minHeight:58,borderRadius:14,borderWidth:1,borderColor:uf===code?s._blue:s._border,backgroundColor:uf===code?'rgba(30,126,245,.09)':s._surface2,padding:9,justifyContent:'center'}}><Text style={{color:uf===code?s._blue:s._text,fontSize:13,fontWeight:'900'}}>{code}</Text><Text style={{color:s._muted,fontSize:8,marginTop:2}}>{name}</Text></TouchableOpacity>)}</ScrollView></View></View></Modal>
  </ScrollView>
}'''
text=text[:start]+screen+text[end:]

# Apuracao screen: dormant until official TSE data becomes active, then 20-second refresh.
insert_at=text.find('\nfunction Settings({onLogout})')
results_screen=r'''
function ResultsScreen(){
  const s=useStyles();const [office,setOffice]=useState('PRESIDENTE'),[uf,setUf]=useState('MG'),[data,setData]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState('');const timer=useRef(null),app=useRef(AppState.currentState);
  const load=async()=>{if(busy)return;setBusy(true);try{const r=await fetch(`${LIVE_RESULTS_API}?office=${encodeURIComponent(office)}&uf=${encodeURIComponent(office==='PRESIDENTE'?'BR':uf)}&t=${Date.now()}`,{headers:{Accept:'application/json','Cache-Control':'no-cache'}});const j=await r.json().catch(()=>null);if(r.ok&&j?.ok){setData(j);setError('')}else throw new Error('SOURCE')}catch{setError('Não consegui consultar a fonte oficial agora.')}finally{setBusy(false)}};
  useEffect(()=>{load()},[office,uf]);
  useEffect(()=>{if(timer.current)clearInterval(timer.current);timer.current=null;if(data?.active)timer.current=setInterval(load,20000);return()=>{if(timer.current)clearInterval(timer.current)}},[data?.active,office,uf]);
  useEffect(()=>{const sub=AppState.addEventListener('change',next=>{if(app.current.match(/inactive|background/)&&next==='active')load();app.current=next});return()=>sub.remove()},[office,uf]);
  const candidates=data?.candidates||[],pct=Number(data?.totals?.percentSections||0);const live=Boolean(data?.active);
  return <ScrollView contentContainerStyle={[s.content,{paddingBottom:118}]}><View style={{flexDirection:'row',justifyContent:'space-between',alignItems:'flex-start',gap:10}}><View style={{flex:1}}><Text style={[s.pageTitle,{fontSize:34}]}>Apuração</Text><Text style={s.pageSub}>Resultados oficiais do TSE. Quando a totalização começar, esta tela entra automaticamente em modo ao vivo.</Text></View><View style={{paddingHorizontal:10,paddingVertical:7,borderRadius:13,backgroundColor:live?'rgba(27,185,110,.12)':'rgba(240,160,32,.12)',borderWidth:1,borderColor:live?'#1BB96E':'#F0A020'}}><Text style={{color:live?'#1BB96E':'#F0A020',fontSize:9,fontWeight:'900'}}>{live?'● AO VIVO':'○ AGUARDANDO'}</Text></View></View>
    <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={{gap:8}}>{[['PRESIDENTE','Presidente'],['GOVERNADOR','Governador'],['SENADOR','Senador'],['DEPUTADO_FEDERAL','Dep. Federal'],[uf==='DF'?'DEPUTADO_DISTRITAL':'DEPUTADO_ESTADUAL',uf==='DF'?'Dep. Distrital':'Dep. Estadual']].map(([k,l])=><TouchableOpacity key={k} onPress={()=>setOffice(k)} style={{paddingVertical:10,paddingHorizontal:14,borderRadius:19,borderWidth:1,borderColor:office===k?s._blue:s._border,backgroundColor:office===k?s._blue:s._surface}}><Text style={{color:office===k?'#fff':s._text,fontSize:9,fontWeight:'900'}}>{l}</Text></TouchableOpacity>)}</ScrollView>
    {office!=='PRESIDENTE'?<TextInput value={uf} onChangeText={v=>setUf(v.toUpperCase().replace(/[^A-Z]/g,'').slice(0,2))} maxLength={2} placeholder="UF" placeholderTextColor={s._muted} style={[s.input,{width:90,textAlign:'center',fontWeight:'900'}]}/>:null}
    <View style={{backgroundColor:s._surface,borderWidth:1,borderColor:s._border,borderRadius:22,padding:18}}><View style={{flexDirection:'row',justifyContent:'space-between',alignItems:'center'}}><View><Text style={{color:s._muted,fontSize:9,fontWeight:'900'}}>TOTALIZAÇÃO DAS SEÇÕES</Text><Text style={{color:s._text,fontSize:32,fontWeight:'900',marginTop:3}}>{live?`${pct.toFixed(2).replace('.',',')}%`:'—'}</Text></View><TouchableOpacity onPress={load} disabled={busy} style={{paddingHorizontal:12,paddingVertical:9,borderRadius:14,borderWidth:1,borderColor:s._border}}><Text style={{color:s._blue,fontSize:9,fontWeight:'900'}}>{busy?'ATUALIZANDO…':'↻ ATUALIZAR'}</Text></TouchableOpacity></View><View style={{height:10,borderRadius:6,backgroundColor:s._surface2,overflow:'hidden',marginTop:12}}><View style={{height:'100%',width:`${Math.max(0,Math.min(100,pct))}%`,backgroundColor:s._blue,borderRadius:6}}/></View><Text style={{color:s._muted,fontSize:9,lineHeight:14,marginTop:10}}>{data?.message||error||'Consultando se a apuração de 2026 já começou.'}</Text>{data?.tseUpdatedAt?<Text style={{color:s._muted,fontSize:8,marginTop:5}}>Última atualização do TSE: {data.tseUpdatedAt}</Text>:null}</View>
    {live&&candidates.length?<View style={{gap:10}}>{candidates.slice(0,40).map((c,i)=><View key={`${c.number}-${c.name}`} style={{backgroundColor:s._surface,borderWidth:1,borderColor:s._border,borderRadius:18,padding:14}}><View style={{flexDirection:'row',alignItems:'center',gap:10}}><Text style={{color:s._muted,fontSize:12,fontWeight:'900',width:24}}>{i+1}º</Text><View style={{flex:1}}><Text style={{color:s._text,fontSize:14,fontWeight:'900'}} numberOfLines={1}>{c.name}</Text><Text style={{color:s._muted,fontSize:9,marginTop:2}}>{c.number}{c.party?` · ${c.party}`:''}</Text></View><View style={{alignItems:'flex-end'}}><Text style={{color:s._blue,fontSize:18,fontWeight:'900'}}>{Number(c.percent||0).toFixed(2).replace('.',',')}%</Text><Text style={{color:s._muted,fontSize:8}}>{Number(c.votes||0).toLocaleString('pt-BR')} votos</Text></View></View></View>)}</View>:<View style={{borderRadius:22,borderWidth:1,borderColor:'rgba(30,126,245,.22)',backgroundColor:'rgba(30,126,245,.04)',padding:18,alignItems:'center'}}><XisOfficial height={120}/><Text style={{color:s._text,fontSize:18,fontWeight:'900',marginTop:6}}>Tudo pronto para o dia da eleição</Text><Text style={{color:s._muted,fontSize:11,lineHeight:17,textAlign:'center',marginTop:7}}>Antes da apuração, não exibimos números fictícios. Assim que o TSE publicar votos totalizados, o modo AO VIVO será ativado e esta tela passará a atualizar a cada 20 segundos enquanto estiver aberta.</Text></View>}
    <Text style={{color:s._muted,fontSize:8,lineHeight:13,textAlign:'center'}}>Fonte exclusiva da apuração: Tribunal Superior Eleitoral (TSE). O RAIO-X apenas organiza a exibição dos dados oficiais.</Text></ScrollView>
}
'''
text=text[:insert_at]+results_screen+text[insert_at:]

p.write_text(text,encoding='utf-8')

replace_once('AppV020.js','<DrawerItem icon="▥" label="Pesquisas" onPress={()=>{onGo(\'Pesquisas\');onClose()}}/>','<DrawerItem icon="▥" label="Pesquisas" onPress={()=>{onGo(\'Pesquisas\');onClose()}}/><DrawerItem icon="◉" label="Apuração" onPress={()=>{onGo(\'Apuração\');onClose()}}/>','drawer apuracao')
replace_once('AppV020.js',":tab==='Pesquisas'?<PollsScreen/>:tab==='Comparar'?<Compare/>",":tab==='Pesquisas'?<PollsScreen/>:tab==='Apuração'?<ResultsScreen/>:tab==='Comparar'?<Compare/>",'router apuracao')
replace_once('AppV020.js',"const VERSION='0.3.32';","const VERSION='0.3.33';",'visible version')
replace_once('AuthGateV020.js',"const APP_VERSION='0.3.32';","const APP_VERSION='0.3.33';",'auth version')
replace_once('XisEngine.js',"'X-App-Version':'0.3.32'","'X-App-Version':'0.3.33'",'Xis version')

app_path=Path('app.json');app=json.loads(app_path.read_text(encoding='utf-8'));expo=app['expo'];expo['version']='0.3.33';expo['android']['versionCode']=37;expo.setdefault('extra',{})['release']='legislative-polls-and-apuracao-v033';expo['extra']['resultsRefreshSeconds']=20;app_path.write_text(json.dumps(app,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
pkg_path=Path('package.json');pkg=json.loads(pkg_path.read_text(encoding='utf-8'));pkg['version']='0.3.33';pkg_path.write_text(json.dumps(pkg,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
print('RAIO-X v0.3.33: legislative polls + district deputy + dormant/live TSE apuracao prepared')
