import patch_v034
from pathlib import Path
import json


def replace_between(text,start_marker,end_marker,new_block,label):
    start=text.find(start_marker)
    end=text.find(end_marker,start)
    if start<0 or end<0:
        raise SystemExit(f'Missing v0.3.35 block: {label}')
    return text[:start]+new_block+text[end:]


def replace_once(text,old,new,label):
    if old not in text:
        raise SystemExit(f'Missing v0.3.35 target: {label}')
    return text.replace(old,new,1)

p=Path('AppV020.js')
text=p.read_text(encoding='utf-8')

# Rebuild the polling visuals from the approved premium mockup instead of styling the old layout.
pollbar=r'''function PollAvatar({name,office,uf,size=44}){
  const wanted=normalize(name||'');
  const c=candidates.find(x=>{const sameName=normalize(x.name||'')===wanted||normalize(x.civilName||'')===wanted;const sameUf=office==='PRESIDENTE'||!uf||normalize(x.uf||'')===normalize(uf);return sameName&&sameUf});
  const src=c?candidatePhotos?.[c.id]:null;
  if(src)return <Image source={src} style={{width:size,height:size,borderRadius:size/2,backgroundColor:'#EEF3F9'}} resizeMode="cover"/>;
  return <View style={{width:size,height:size,borderRadius:size/2,backgroundColor:'#EEF4FB',borderWidth:1,borderColor:'#D8E4F1',alignItems:'center',justifyContent:'center'}}><Text style={{color:'#0A2A55',fontSize:Math.max(12,size*.34),fontWeight:'900'}}>{String(name||'?').slice(0,1).toUpperCase()}</Text></View>
}

function PollBar({name,party,pct,leader=false,favorite=false,compact=false}){
  const pctNum=Number(pct||0),barWidth=`${Math.min(100,Math.max(pctNum?3:0,pctNum*2.18))}%`;
  return <View style={{marginTop:compact?8:12,padding:favorite?7:0,borderRadius:12,backgroundColor:favorite?'#FFF8E8':'transparent',borderWidth:favorite?1:0,borderColor:'#F0CF79'}}>
    <View style={{flexDirection:'row',alignItems:'center',justifyContent:'space-between',gap:7}}><View style={{flex:1,flexDirection:'row',alignItems:'center',gap:6}}><Text style={{color:'#0B1D3A',fontSize:compact?9:12,fontWeight:'800',flexShrink:1}} numberOfLines={1}>{name}{party?` (${party})`:''}</Text>{favorite?<View style={{paddingHorizontal:5,paddingVertical:2,borderRadius:6,backgroundColor:'#FFF0BD'}}><Text style={{color:'#A96A00',fontSize:6,fontWeight:'900'}}>★ FAVORITO</Text></View>:leader?<View style={{paddingHorizontal:5,paddingVertical:2,borderRadius:6,borderWidth:1,borderColor:'#1677FF'}}><Text style={{color:'#1677FF',fontSize:6,fontWeight:'900'}}>LIDERA</Text></View>:null}</View><Text style={{color:favorite?'#B87800':'#126FEA',fontSize:compact?10:15,fontWeight:'900'}}>{pctNum}%</Text></View>
    <View style={{height:compact?5:7,borderRadius:5,backgroundColor:'#EEF3F9',overflow:'hidden',marginTop:5}}><View style={{height:'100%',width:barWidth,borderRadius:5,backgroundColor:favorite?'#E6A51B':'#1677FF'}}/></View>
  </View>
}'''
text=replace_between(text,'function PollBar(','\nfunction PollCard(',pollbar,'PollBar')

pollcard=r'''function PollCard({poll}){
  const {matchesName}=useFavorites();const purple=poll.institute==='Quaest',badge=(poll.institute||'?').slice(0,1).toUpperCase();
  const labels={PRESIDENTE:'Presidente · 1º turno',GOVERNADOR:`Governador · ${poll.uf}`,SENADOR:`Senador · ${poll.uf}`,DEPUTADO_FEDERAL:`Deputado Federal · ${poll.uf}`,DEPUTADO_ESTADUAL:`Deputado Estadual · ${poll.uf}`,DEPUTADO_DISTRITAL:'Deputado Distrital · DF'};
  const officeLabel=labels[poll.office]||'Pesquisa eleitoral';
  return <View style={{backgroundColor:'#FFFFFF',borderWidth:1,borderColor:'#DFE8F3',borderRadius:20,padding:15,shadowColor:'#00152F',shadowOpacity:.06,shadowRadius:10,shadowOffset:{width:0,height:4},elevation:2}}>
    <View style={{flexDirection:'row',alignItems:'center',justifyContent:'space-between',gap:9}}><View style={{flexDirection:'row',alignItems:'center',gap:10,flex:1}}><View style={{width:40,height:40,borderRadius:20,backgroundColor:purple?'#6F2DBD':'#1677FF',alignItems:'center',justifyContent:'center'}}><Text style={{color:'#FFFFFF',fontSize:20,fontWeight:'900'}}>{badge}</Text></View><View style={{flex:1}}><Text style={{color:'#071B39',fontSize:19,fontWeight:'900'}}>{poll.institute}</Text><Text style={{color:'#63758C',fontSize:9,marginTop:1}}>{officeLabel}</Text></View></View><Text style={{color:'#1677FF',fontSize:9,fontWeight:'900'}}>{poll.published}</Text></View>
    <View style={{marginTop:12,paddingVertical:10,borderTopWidth:1,borderBottomWidth:1,borderColor:'#E7EEF6'}}>{poll.mode?<Text style={{color:'#1677FF',fontSize:8,fontWeight:'900',marginBottom:4}}>{String(poll.mode).toUpperCase()}</Text>:null}{poll.question?<Text style={{color:'#26384D',fontSize:9,lineHeight:13,marginBottom:6}}>{poll.question}</Text>:null}<Text style={{color:'#65778E',fontSize:9,lineHeight:15}}>▣ Campo: {poll.field||'—'}</Text><Text style={{color:'#65778E',fontSize:9,lineHeight:15}}>♟ Amostra: {Number(poll.sample||0).toLocaleString('pt-BR')}     ◉ Margem: ±{poll.margin||0} p.p.</Text><Text style={{color:'#65778E',fontSize:9,lineHeight:15}}>▤ Registro TSE: {poll.registry||'—'}</Text></View>
    <View>{(poll.results||[]).map(([n,party,v],i)=><PollBar key={`${poll.id}-${n}`} name={n} party={party} pct={v} leader={i===0} favorite={matchesName(n,poll.office,poll.uf)}/>)}</View>
    {poll.sourceUrl?<TouchableOpacity onPress={()=>Linking.openURL(poll.sourceUrl)} style={{marginTop:14,height:39,borderRadius:14,borderWidth:1,borderColor:'#E1E9F2',alignItems:'center',justifyContent:'center'}}><Text style={{color:'#10233E',fontSize:10,fontWeight:'800'}}>Ver detalhes   ›</Text></TouchableOpacity>:null}
  </View>
}'''
text=replace_between(text,'function PollCard({poll})','\nfunction PollComparison(',pollcard,'PollCard')

comparison=r'''function PollComparison({polls,office='PRESIDENTE',uf='BR'}){
  const df=(polls||[]).find(p=>p.institute==='Datafolha'),qu=(polls||[]).find(p=>p.institute==='Quaest');if(!df||!qu)return null;
  const title=office==='PRESIDENTE'?'Comparativo Nacional':`Comparativo ${uf}`;
  const renderCol=poll=>{const top=(poll.results||[])[0]||['—','',0];return <View style={{flex:1,minWidth:0}}><View style={{flexDirection:'row',alignItems:'center',gap:8,marginBottom:8}}><PollAvatar name={top[0]} office={office} uf={uf} size={46}/><View style={{flex:1,minWidth:0}}><View style={{flexDirection:'row',alignItems:'center',gap:5}}><Text style={{color:'#0B1D3A',fontSize:13,fontWeight:'900',flexShrink:1}} numberOfLines={1}>{top[0]}{top[1]?` (${top[1]})`:''}</Text></View><Text style={{color:'#6D7C91',fontSize:8,marginTop:2}}>{poll.institute}</Text></View></View><PollBar name={top[0]} party={top[1]} pct={top[2]} leader compact/>{(poll.results||[]).slice(1,6).map(([n,p,v])=><PollBar key={`${poll.id}-${n}`} name={n} party={p} pct={v} compact/>)}</View>};
  return <View style={{backgroundColor:'#FFFFFF',borderWidth:1,borderColor:'#DFE8F3',borderRadius:20,padding:15,shadowColor:'#00152F',shadowOpacity:.05,shadowRadius:10,elevation:2}}><View style={{flexDirection:'row',alignItems:'center',justifyContent:'space-between',gap:8}}><Text style={{color:'#071B39',fontSize:17,fontWeight:'900',flex:1}}>{title} — Datafolha × Quaest</Text><Text style={{color:'#1677FF',fontSize:20}}>▥</Text></View><View style={{flexDirection:'row',gap:12,marginTop:13}}>{renderCol(df)}<View style={{width:1,backgroundColor:'#E5ECF4'}}/>{renderCol(qu)}</View><Text style={{color:'#7A899C',fontSize:7,lineHeight:11,marginTop:12}}>Compare sempre instituto, período de campo, amostra e margem de erro. Pesquisas diferentes são retratos independentes.</Text></View>
}'''
text=replace_between(text,'function PollComparison(','\nfunction PollsScreen(){',comparison,'PollComparison')

polls_screen=r'''function PollsScreen(){
  const [category,setCategory]=useState('PRESIDENTE'),[deputyKind,setDeputyKind]=useState('FEDERAL'),[uf,setUf]=useState('MG'),[source,setSource]=useState('Todas');
  const [locationPrompt,setLocationPrompt]=useState(false),[statePicker,setStatePicker]=useState(false),[locationBusy,setLocationBusy]=useState(false),[prefsReady,setPrefsReady]=useState(false),[locationDecision,setLocationDecision]=useState('');
  const UFS=[['AC','Acre'],['AL','Alagoas'],['AP','Amapá'],['AM','Amazonas'],['BA','Bahia'],['CE','Ceará'],['DF','Distrito Federal'],['ES','Espírito Santo'],['GO','Goiás'],['MA','Maranhão'],['MT','Mato Grosso'],['MS','Mato Grosso do Sul'],['MG','Minas Gerais'],['PA','Pará'],['PB','Paraíba'],['PR','Paraná'],['PE','Pernambuco'],['PI','Piauí'],['RJ','Rio de Janeiro'],['RN','Rio Grande do Norte'],['RS','Rio Grande do Sul'],['RO','Rondônia'],['RR','Roraima'],['SC','Santa Catarina'],['SP','São Paulo'],['SE','Sergipe'],['TO','Tocantins']];
  const UF_BY_NAME=Object.fromEntries(UFS.map(([code,name])=>[normalize(name),code]));const LOCATION_UF_KEY='raiox.polls.uf.v032',LOCATION_DECISION_KEY='raiox.polls.location.decision.v032';
  const MG_BOOTSTRAP=[{id:'df-mg-gov-2108',institute:'Datafolha',office:'GOVERNADOR',uf:'MG',published:'21/08/2026',field:'18 a 20/08/2026',sample:1204,margin:3,registry:'MG-00446/2026',sourceUrl:'https://www1.folha.uol.com.br/poder/2026/08/datafolha-cleitinho-lidera-disputa-em-mg-com-32-patrus-e-kalil-tem-12-cada.shtml',mode:'Estimulada',question:'Governador de Minas Gerais - 1º turno',results:[['Cleitinho Azevedo','Republicanos',32],['Patrus Ananias','PT',12],['Alexandre Kalil','PDT',12],['Mateus Simões','PSD',4],['Flávio Roscoe','PL',4],['Gabriel Azevedo','MDB',4],['Branco/Nulo','',14],['Indecisos','',13]]}];
  const [scopes,setScopes]=useState({'PRESIDENTE:BR':{polls:POLL_SNAPSHOT,updatedAt:null,note:''},'GOVERNADOR:MG':{polls:MG_BOOTSTRAP,updatedAt:null,note:'Última carga verificada; buscando atualização'}}),[syncingKey,setSyncingKey]=useState('');const appState=useRef(AppState.currentState),inFlight=useRef(new Set());
  const office=category==='DEPUTADOS'?(deputyKind==='FEDERAL'?'DEPUTADO_FEDERAL':uf==='DF'?'DEPUTADO_DISTRITAL':'DEPUTADO_ESTADUAL'):category;const scopeKey=(o=office,u=uf)=>o==='PRESIDENTE'?'PRESIDENTE:BR':`${o}:${String(u||'MG').toUpperCase().slice(0,2)}`;const cacheKey=k=>`${POLLS_CACHE_KEY}.${k}`,currentKey=scopeKey(),current=scopes[currentKey]||{polls:[],updatedAt:null,note:''};
  const saveScope=async(k,value)=>{try{await SecureStore.setItemAsync(cacheKey(k),JSON.stringify(value))}catch{}};const loadScope=async(k)=>{try{const raw=await SecureStore.getItemAsync(cacheKey(k));if(!raw)return null;const v=JSON.parse(raw);return Array.isArray(v?.polls)&&v.polls.length?v:null}catch{return null}};const setScope=async(k,polls,at,note)=>{if(!Array.isArray(polls)||!polls.length)return false;const value={polls,updatedAt:at||new Date().toISOString(),note:note||''};setScopes(prev=>({...prev,[k]:value}));await saveScope(k,value);return true};
  const refresh=async(nextOffice=office,nextUf=uf)=>{const o=nextOffice||'PRESIDENTE',u=o==='PRESIDENTE'?'BR':String(nextUf||'MG').toUpperCase().slice(0,2),k=scopeKey(o,u);if(inFlight.current.has(k))return;inFlight.current.add(k);setSyncingKey(k);setScopes(prev=>({...prev,[k]:{...(prev[k]||{polls:[],updatedAt:null}),note:'Atualizando…'}}));try{const r=await fetch(`${LIVE_POLLS_API}?office=${encodeURIComponent(o)}&uf=${encodeURIComponent(u)}&t=${Date.now()}`,{headers:{Accept:'application/json','Cache-Control':'no-cache'}});const data=await r.json().catch(()=>null);if(r.ok&&data?.ok&&Array.isArray(data.polls)&&data.polls.length){await setScope(k,data.polls,data.fetchedAt,data.fresh?'Atualizado agora':'Última carga válida mantida');return}setScopes(prev=>({...prev,[k]:{...(prev[k]||{polls:[],updatedAt:null}),updatedAt:data?.fetchedAt||prev[k]?.updatedAt||null,note:data?.warning||'Nenhuma pesquisa registrada e verificável encontrada.'}}))}catch{const cached=await loadScope(k);if(cached)setScopes(prev=>({...prev,[k]:{...cached,note:'Sem conexão; última carga válida mantida'}}));else setScopes(prev=>({...prev,[k]:{...(prev[k]||{polls:[],updatedAt:null}),note:'Sem conexão com as fontes'}}))}finally{inFlight.current.delete(k);setSyncingKey(v=>v===k?'':v)}};
  const markLocationDecision=async value=>{setLocationDecision(value);try{await SecureStore.setItemAsync(LOCATION_DECISION_KEY,value)}catch{}};const selectUf=async code=>{if(!UFS.some(([c])=>c===code))return;setUf(code);setStatePicker(false);setLocationPrompt(false);await markLocationDecision('manual');try{await SecureStore.setItemAsync(LOCATION_UF_KEY,code)}catch{}};
  const detectState=async()=>{if(locationBusy)return;setLocationBusy(true);try{const permission=await Location.requestForegroundPermissionsAsync();if(permission.status!=='granted'){await markLocationDecision('denied');setLocationPrompt(false);return}const pos=await Location.getCurrentPositionAsync({accuracy:Location.Accuracy.Low});const places=await Location.reverseGeocodeAsync({latitude:pos.coords.latitude,longitude:pos.coords.longitude});const place=places?.[0]||{},country=normalize(place.isoCountryCode||place.country||'');let region=normalize(place.region||place.subregion||'').replace(/^ESTADO DE /,'').replace(/^STATE OF /,'');const detected=UF_BY_NAME[region]||(UFS.some(([c])=>c===region)?region:'');if(!detected||!(country==='BR'||country==='BRA'||country==='BRASIL'||country==='BRAZIL')){await markLocationDecision('granted');setLocationPrompt(false);setStatePicker(true);return}setUf(detected);setLocationPrompt(false);setStatePicker(false);await markLocationDecision('granted');try{await SecureStore.setItemAsync(LOCATION_UF_KEY,detected)}catch{}}catch{setLocationPrompt(false);setStatePicker(true)}finally{setLocationBusy(false)}};
  useEffect(()=>{let active=true;(async()=>{try{const savedUf=await SecureStore.getItemAsync(LOCATION_UF_KEY),decision=await SecureStore.getItemAsync(LOCATION_DECISION_KEY);if(active&&savedUf&&UFS.some(([c])=>c===savedUf))setUf(savedUf);if(active)setLocationDecision(decision||'')}catch{}finally{if(active)setPrefsReady(true)}for(const k of ['PRESIDENTE:BR','GOVERNADOR:MG']){const c=await loadScope(k);if(active&&c)setScopes(prev=>({...prev,[k]:c}))}if(active)refresh('PRESIDENTE','BR')})();return()=>{active=false}},[]);useEffect(()=>{if(prefsReady&&category!=='PRESIDENTE'&&!locationDecision)setLocationPrompt(true)},[prefsReady,category,locationDecision]);useEffect(()=>{const sub=AppState.addEventListener('change',next=>{if(appState.current.match(/inactive|background/)&&next==='active')refresh(office,uf);appState.current=next});return()=>sub.remove()},[office,uf]);useEffect(()=>{refresh(office,uf)},[office,uf]);
  const rows=(current.polls||[]).filter(p=>source==='Todas'||p.institute===source),stamp=current.updatedAt?new Date(current.updatedAt):null,stampText=stamp&&!Number.isNaN(stamp.getTime())?stamp.toLocaleString('pt-BR',{hour:'2-digit',minute:'2-digit',day:'2-digit',month:'2-digit'}):'carga local verificada',syncing=syncingKey===currentKey;const leaders=rows.filter(p=>p.results?.length).map(p=>p.results[0][0]),unique=[...new Set(leaders)],summary=leaders.length?(unique.length===1?`${unique[0]} aparece numericamente à frente nos levantamentos exibidos. Compare sempre instituto, data e margem de erro.`:'Os levantamentos exibidos têm resultados diferentes. Compare sempre instituto, data e margem de erro.'):'Ainda não encontrei levantamento registrado e verificável para este filtro.';const officeLabel={PRESIDENTE:'Presidente',GOVERNADOR:'Governador',SENADOR:'Senador',DEPUTADO_FEDERAL:'Deputado Federal',DEPUTADO_ESTADUAL:'Deputado Estadual',DEPUTADO_DISTRITAL:'Deputado Distrital'}[office]||office;
  const categoryTabs=[['PRESIDENTE','♟','Presidente'],['GOVERNADOR','♜','Governador'],['SENADOR','◉','Senador'],['DEPUTADOS','▤','Deputados']];
  return <><ScrollView style={{backgroundColor:'#F8FBFF'}} contentContainerStyle={{paddingHorizontal:16,paddingTop:18,paddingBottom:120}} keyboardShouldPersistTaps="handled"><View style={{flexDirection:'row',alignItems:'flex-start',justifyContent:'space-between',gap:10}}><View style={{flex:1}}><Text style={{color:'#071B39',fontSize:34,fontWeight:'900',letterSpacing:-1}}>Pesquisas</Text><Text style={{color:'#526983',fontSize:13,lineHeight:19,marginTop:4}}>Acompanhe levantamentos eleitorais de forma clara, bonita e comparável.</Text></View><TouchableOpacity onPress={()=>refresh(office,uf)} disabled={syncing} style={{width:42,height:42,borderRadius:15,borderWidth:1,borderColor:'#D8E4F1',backgroundColor:'#FFFFFF',alignItems:'center',justifyContent:'center'}}><Text style={{color:'#1677FF',fontSize:18,fontWeight:'900'}}>↻</Text></TouchableOpacity></View>
    <View style={{flexDirection:'row',alignItems:'center',gap:6,marginTop:10,marginBottom:13}}><View style={{width:8,height:8,borderRadius:4,backgroundColor:syncing?'#F0A020':'#20B779'}}/><Text style={{color:'#6E8096',fontSize:9}}>Última atualização: {stampText}{syncing?' · atualizando…':''}</Text></View>
    <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={{gap:8,paddingBottom:10}}>{categoryTabs.map(([k,icon,label])=><TouchableOpacity key={k} onPress={()=>setCategory(k)} style={{height:45,paddingHorizontal:15,borderRadius:22,borderWidth:1,borderColor:category===k?'#1677FF':'#D8E4F1',backgroundColor:category===k?'#1677FF':'#FFFFFF',flexDirection:'row',alignItems:'center',gap:7}}><Text style={{color:category===k?'#FFFFFF':'#36506E',fontSize:13}}>{icon}</Text><Text style={{color:category===k?'#FFFFFF':'#263A55',fontSize:10,fontWeight:'900'}}>{label}</Text></TouchableOpacity>)}</ScrollView>
    {category==='DEPUTADOS'?<View style={{flexDirection:'row',gap:8,marginBottom:9}}><TouchableOpacity onPress={()=>setDeputyKind('FEDERAL')} style={{paddingVertical:9,paddingHorizontal:16,borderRadius:16,borderWidth:1,borderColor:deputyKind==='FEDERAL'?'#1677FF':'#D8E4F1',backgroundColor:deputyKind==='FEDERAL'?'#EAF3FF':'#FFFFFF'}}><Text style={{color:deputyKind==='FEDERAL'?'#1677FF':'#263A55',fontSize:9,fontWeight:'900'}}>Federal</Text></TouchableOpacity><TouchableOpacity onPress={()=>setDeputyKind('LOCAL')} style={{paddingVertical:9,paddingHorizontal:16,borderRadius:16,borderWidth:1,borderColor:deputyKind==='LOCAL'?'#1677FF':'#D8E4F1',backgroundColor:deputyKind==='LOCAL'?'#EAF3FF':'#FFFFFF'}}><Text style={{color:deputyKind==='LOCAL'?'#1677FF':'#263A55',fontSize:9,fontWeight:'900'}}>{uf==='DF'?'Distrital':'Estadual'}</Text></TouchableOpacity></View>:null}
    {category!=='PRESIDENTE'?<View style={{flexDirection:'row',alignItems:'center',gap:8,marginBottom:10}}><TouchableOpacity onPress={()=>setStatePicker(true)} style={{height:43,paddingHorizontal:14,borderRadius:16,borderWidth:1,borderColor:'#D8E4F1',backgroundColor:'#FFFFFF',flexDirection:'row',alignItems:'center',gap:7}}><Text style={{color:'#6F8197',fontSize:8,fontWeight:'900'}}>ESTADO</Text><Text style={{color:'#0B1D3A',fontSize:13,fontWeight:'900'}}>{uf}</Text><Text style={{color:'#1677FF',fontSize:10}}>⌄</Text></TouchableOpacity><TouchableOpacity onPress={detectState} disabled={locationBusy} style={{height:43,paddingHorizontal:13,borderRadius:16,borderWidth:1,borderColor:'#BBD7F8',backgroundColor:'#F3F8FF',flexDirection:'row',alignItems:'center',gap:5}}><Text style={{color:'#1677FF',fontSize:14}}>⌖</Text><Text style={{color:'#1677FF',fontSize:8,fontWeight:'900'}}>{locationBusy?'LOCALIZANDO…':'MEU ESTADO'}</Text></TouchableOpacity></View>:null}
    <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={{gap:8,paddingBottom:13}}>{['Todas','Datafolha','Quaest'].map(x=><TouchableOpacity key={x} onPress={()=>setSource(x)} style={{height:42,paddingHorizontal:18,borderRadius:21,borderWidth:1,borderColor:source===x?'#1677FF':'#D8E4F1',backgroundColor:source===x?'#1677FF':'#FFFFFF',alignItems:'center',justifyContent:'center'}}><Text style={{color:source===x?'#FFFFFF':'#263A55',fontSize:9,fontWeight:'900'}}>{x}</Text></TouchableOpacity>)}</ScrollView>
    <View style={{backgroundColor:'#F4F9FF',borderWidth:1,borderColor:'#AFCFF4',borderRadius:22,padding:15,marginBottom:13,overflow:'hidden'}}><View style={{flexDirection:'row',alignItems:'center',gap:14}}><View style={{width:112,height:124,alignItems:'center',justifyContent:'flex-end'}}><XisOfficial height={122}/></View><View style={{flex:1}}><Text style={{color:'#071B39',fontSize:19,fontWeight:'900'}}>Resumo do Xis</Text><Text style={{color:'#435A75',fontSize:11,lineHeight:18,marginTop:7}}>{summary}</Text></View><Text style={{color:'#FFFFFF',fontSize:43,textShadowColor:'#9DC8FF',textShadowRadius:10}}>ϟ</Text></View></View>
    {rows.length?<>{source==='Todas'?<View style={{marginBottom:13}}><PollComparison polls={rows} office={office} uf={uf}/></View>:null}<View style={{gap:12}}>{rows.map(p=><PollCard key={p.id} poll={p}/>)}</View></>:<View style={{backgroundColor:'#FFFFFF',borderWidth:1,borderColor:'#DFE8F3',borderRadius:20,padding:18}}><Text style={{color:'#071B39',fontSize:18,fontWeight:'900'}}>{syncing?'Buscando pesquisas…':'Nenhuma pesquisa verificável encontrada'}</Text><Text style={{color:'#63758C',fontSize:10,lineHeight:16,marginTop:6}}>{syncing?'Consultando as fontes agora.':`Não encontramos levantamento publicado e verificável para ${officeLabel}${office==='PRESIDENTE'?'':` · ${uf}`}. Quando houver, aparecerá automaticamente.`}</Text></View>}
    <TouchableOpacity onPress={()=>Linking.openURL(TSE_POLLS)} style={{height:44,borderRadius:15,borderWidth:1,borderColor:'#BFD6EE',backgroundColor:'#FFFFFF',alignItems:'center',justifyContent:'center',marginTop:13}}><Text style={{color:'#126FEA',fontSize:9,fontWeight:'900'}}>ABRIR PESQUISAS NO TSE</Text></TouchableOpacity><Text style={{color:'#7A899C',fontSize:8,lineHeight:13,textAlign:'center',marginTop:9}}>Pesquisa é um retrato do momento, não previsão do resultado. Em deputados, preservamos o tipo original do levantamento.</Text></ScrollView>
    <Modal visible={locationPrompt} transparent statusBarTranslucent animationType="fade" onRequestClose={()=>setLocationPrompt(false)}><View style={{flex:1,backgroundColor:'rgba(2,18,42,.68)',justifyContent:'center',paddingHorizontal:22}}><View style={{backgroundColor:'#FFFFFF',borderRadius:25,padding:20,borderWidth:1,borderColor:'#DCE6F1',shadowColor:'#000',shadowOpacity:.18,shadowRadius:20,elevation:18}}><View style={{alignItems:'center'}}><View style={{width:58,height:58,borderRadius:20,backgroundColor:'#EEF6FF',alignItems:'center',justifyContent:'center'}}><Text style={{color:'#1677FF',fontSize:28}}>⌖</Text></View><Text style={{color:'#071B39',fontSize:22,fontWeight:'900',textAlign:'center',marginTop:12}}>Pesquisas do seu estado</Text><Text style={{color:'#526983',fontSize:11,lineHeight:17,textAlign:'center',marginTop:8}}>Posso usar sua localização aproximada para selecionar automaticamente a UF?</Text></View><View style={{marginTop:13,padding:12,borderRadius:14,backgroundColor:'#F3F7FB',borderWidth:1,borderColor:'#E3EBF4'}}><Text style={{color:'#31465F',fontSize:9,lineHeight:14,textAlign:'center'}}>Usamos a localização somente para descobrir o estado. As coordenadas não são enviadas ao servidor nem ficam salvas.</Text></View><TouchableOpacity disabled={locationBusy} onPress={detectState} style={{marginTop:15,height:50,borderRadius:16,backgroundColor:'#1677FF',alignItems:'center',justifyContent:'center'}}><Text style={{color:'#FFFFFF',fontSize:10,fontWeight:'900'}}>{locationBusy?'LOCALIZANDO…':'USAR MEU ESTADO'}</Text></TouchableOpacity><TouchableOpacity onPress={()=>{setLocationPrompt(false);setStatePicker(true)}} style={{marginTop:9,height:48,borderRadius:16,borderWidth:1,borderColor:'#CAD8E7',backgroundColor:'#FFFFFF',alignItems:'center',justifyContent:'center'}}><Text style={{color:'#10233E',fontSize:10,fontWeight:'900'}}>ESCOLHER ESTADO</Text></TouchableOpacity><TouchableOpacity onPress={async()=>{setLocationPrompt(false);await markLocationDecision('denied')}} style={{height:42,alignItems:'center',justifyContent:'center'}}><Text style={{color:'#75879C',fontSize:10,fontWeight:'700'}}>Agora não</Text></TouchableOpacity></View></View></Modal>
    <Modal visible={statePicker} transparent statusBarTranslucent animationType="slide" onRequestClose={()=>setStatePicker(false)}><View style={{flex:1,backgroundColor:'rgba(2,18,42,.62)',justifyContent:'flex-end'}}><View style={{maxHeight:'78%',backgroundColor:'#FFFFFF',borderTopLeftRadius:28,borderTopRightRadius:28,padding:18,shadowColor:'#000',shadowOpacity:.18,shadowRadius:16,elevation:18}}><View style={{flexDirection:'row',alignItems:'center',justifyContent:'space-between',marginBottom:12}}><View><Text style={{color:'#071B39',fontSize:20,fontWeight:'900'}}>Escolha o estado</Text><Text style={{color:'#6F8197',fontSize:9,marginTop:2}}>Você pode trocar quando quiser.</Text></View><TouchableOpacity onPress={()=>setStatePicker(false)} style={{width:38,height:38,borderRadius:19,backgroundColor:'#F0F4F8',alignItems:'center',justifyContent:'center'}}><Text style={{color:'#0B1D3A',fontSize:20}}>×</Text></TouchableOpacity></View><ScrollView contentContainerStyle={{flexDirection:'row',flexWrap:'wrap',gap:8,paddingBottom:24}}>{UFS.map(([code,name])=><TouchableOpacity key={code} onPress={()=>selectUf(code)} style={{width:'31%',minHeight:59,borderRadius:14,borderWidth:1,borderColor:uf===code?'#1677FF':'#DCE6F1',backgroundColor:uf===code?'#EEF6FF':'#F8FAFC',padding:9,justifyContent:'center'}}><Text style={{color:uf===code?'#1677FF':'#10233E',fontSize:13,fontWeight:'900'}}>{code}</Text><Text style={{color:'#6F8197',fontSize:8,marginTop:2}} numberOfLines={2}>{name}</Text></TouchableOpacity>)}</ScrollView></View></View></Modal></>
}'''
text=replace_between(text,'function PollsScreen(){','\nfunction ResultsScreen(){',polls_screen,'PollsScreen')

# Version bump.
text=replace_once(text,"const VERSION='0.3.34';","const VERSION='0.3.35';",'visible version')
p.write_text(text,encoding='utf-8')

a=Path('AuthGateV020.js');at=a.read_text(encoding='utf-8');at=replace_once(at,"const APP_VERSION='0.3.34';","const APP_VERSION='0.3.35';",'AuthGate version');a.write_text(at,encoding='utf-8')
x=Path('XisEngine.js');xt=x.read_text(encoding='utf-8');xt=replace_once(xt,"'X-App-Version':'0.3.34'","'X-App-Version':'0.3.35'",'Xis header version');x.write_text(xt,encoding='utf-8')
app_path=Path('app.json');app=json.loads(app_path.read_text(encoding='utf-8'));app['expo']['version']='0.3.35';app['expo']['android']['versionCode']=39;app['expo'].setdefault('extra',{})['release']='approved-polls-layout-v035';app_path.write_text(json.dumps(app,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
pkg_path=Path('package.json');pkg=json.loads(pkg_path.read_text(encoding='utf-8'));pkg['version']='0.3.35';pkg_path.write_text(json.dumps(pkg,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
print('RAIO-X v0.3.35: approved Pesquisas mockup rebuilt + solid location modals applied')
