const MODEL='gpt-5.4-nano';
const OFFICES=new Set(['PRESIDENTE','GOVERNADOR','SENADOR','DEPUTADO_FEDERAL','DEPUTADO_ESTADUAL','DEPUTADO_DISTRITAL']);

const PRESIDENT_FALLBACK=[
  {id:'df-br-2108',institute:'Datafolha',published:'21/08/2026',field:'18 a 20/08/2026',sample:2058,margin:2,registry:'BR-04496/2026',sourceUrl:'https://www1.folha.uol.com.br/poder/2026/08/datafolha-lula-marca-39-no-1o-turno-e-flavio-bolsonaro-tem-33.shtml',question:'Presidente - 1º turno',mode:'Estimulada',results:[['Lula','PT',39],['Flavio Bolsonaro','PL',33],['Ronaldo Caiado','PSD',5],['Renan Santos','Missao',4],['Romeu Zema','Novo',3],['Augusto Cury','Avante',2],['Branco/Nulo','',8],['Nao sabe','',3]]},
  {id:'quaest-br-1408',institute:'Quaest',published:'14/08/2026',field:'10 a 13/08/2026',sample:2004,margin:2,registry:'BR-06773/2026',sourceUrl:'https://quaest.com.br/relatorios/pesquisa-de-intencao-de-voto-para-presidente-1ot-rodada-1-14-08-2026/',question:'Presidente - 1º turno',mode:'Estimulada',results:[['Lula','PT',38],['Flavio Bolsonaro','PL',31],['Renan Santos','Missao',4],['Ronaldo Caiado','PSD',4],['Augusto Cury','Avante',2],['Romeu Zema','Novo',2],['Samara Martins','UP',1],['Branco/Nulo','',8],['Indecisos','',10]]}
];
const MG_GOVERNOR_FALLBACK=[
  {id:'df-mg-gov-2108',institute:'Datafolha',published:'21/08/2026',field:'18 a 20/08/2026',sample:1204,margin:3,registry:'MG-00446/2026',sourceUrl:'https://www1.folha.uol.com.br/poder/2026/08/datafolha-cleitinho-lidera-disputa-em-mg-com-32-patrus-e-kalil-tem-12-cada.shtml',question:'Governador de Minas Gerais - 1º turno',mode:'Estimulada',results:[['Cleitinho Azevedo','Republicanos',32],['Patrus Ananias','PT',12],['Alexandre Kalil','PDT',12],['Mateus Simões','PSD',4],['Flávio Roscoe','PL',4],['Gabriel Azevedo','MDB',4],['Branco/Nulo','',14],['Indecisos','',13]]},
  {id:'quaest-mg-gov-2807',institute:'Quaest',published:'28/07/2026',field:'22 a 26/07/2026',sample:1482,margin:3,registry:'MG-03490/2026',sourceUrl:'https://quaest.com.br/pesquisa-genial-quaest-eleicoes-em-minas-e-pernambuco/',question:'Governador de Minas Gerais - 1º turno',mode:'Estimulada',results:[['Cleitinho Azevedo','Republicanos',35],['Alexandre Kalil','PDT',12],['Patrus Ananias','PT',10],['Mateus Simões','PSD',6],['Gabriel Azevedo','MDB',4],['Indecisos','',15],['Branco/Nulo/Não vai votar','',13]]}
];

function send(res,status,body,cache='public, s-maxage=900, stale-while-revalidate=3600'){res.statusCode=status;res.setHeader('Content-Type','application/json; charset=utf-8');res.setHeader('Cache-Control',cache);res.end(JSON.stringify(body))}
function clean(v,max=300){return String(v??'').replace(/[\u0000-\u001F\u007F]/g,' ').replace(/\s+/g,' ').trim().slice(0,max)}
function textFromResponse(data){if(typeof data?.output_text==='string'&&data.output_text.trim())return data.output_text.trim();const parts=[];for(const item of Array.isArray(data?.output)?data.output:[])for(const c of Array.isArray(item?.content)?item.content:[])if((c?.type==='output_text'||c?.type==='text')&&c.text)parts.push(c.text);return parts.join('\n').trim()}
function parseJson(text){const raw=String(text||'').trim().replace(/^```(?:json)?\s*/i,'').replace(/```$/,'').trim();const a=raw.indexOf('{'),b=raw.lastIndexOf('}');if(a<0||b<=a)throw new Error('NO_JSON');return JSON.parse(raw.slice(a,b+1))}
function dateScore(v){const m=String(v||'').match(/(\d{2})\/(\d{2})\/(\d{4})/);return m?Number(`${m[3]}${m[2]}${m[1]}`):0}
function safeUrl(url){const u=String(url||'');return /^https:\/\//i.test(u)&&!/(facebook\.com|instagram\.com|tiktok\.com|twitter\.com|x\.com)/i.test(u)?u:''}
function normalizePoll(p,office,uf){const institute=clean(p?.institute,80);if(!p||!institute)return null;const results=(Array.isArray(p.results)?p.results:[]).map(r=>[clean(r?.[0],90),clean(r?.[1],30),Number(r?.[2])]).filter(r=>r[0]&&Number.isFinite(r[2])&&r[2]>=0&&r[2]<=100);const registry=clean(p.registry,40),sourceUrl=safeUrl(p.sourceUrl);if(results.length<2||!sourceUrl||!/^([A-Z]{2}|BR)-\d{5}\/2026$/.test(registry))return null;return {id:clean(p.id||`${institute}-${office}-${uf}-${p.published||Date.now()}`,120),institute,office,uf,published:clean(p.published,20),field:clean(p.field,60),sample:Number(p.sample)||null,margin:Number(p.margin)||null,registry,sourceUrl,question:clean(p.question||'',150),mode:clean(p.mode||'',50),results}}
function fallbackFor(office,uf){if(office==='PRESIDENTE')return PRESIDENT_FALLBACK.map(p=>({...p,office:'PRESIDENTE',uf:'BR'}));if(office==='GOVERNADOR'&&uf==='MG')return MG_GOVERNOR_FALLBACK.map(p=>({...p,office:'GOVERNADOR',uf:'MG'}));return []}
function mergePolls(fresh,fallback){const map=new Map();for(const p of [...fallback,...fresh]){const key=`${String(p.institute).toUpperCase()}|${p.mode||''}|${p.question||''}`;const old=map.get(key);if(!old||dateScore(p.published)>dateScore(old.published))map.set(key,p)}return [...map.values()].sort((a,b)=>dateScore(b.published)-dateScore(a.published)).slice(0,8)}
function targetFor(office,uf){if(office==='PRESIDENTE')return 'Presidente da República';if(office==='GOVERNADOR')return `Governador de ${uf}`;if(office==='SENADOR')return `Senador por ${uf}`;if(office==='DEPUTADO_FEDERAL')return `Deputado Federal por ${uf}`;if(office==='DEPUTADO_DISTRITAL')return 'Deputado Distrital no Distrito Federal';return `Deputado Estadual por ${uf}`}
async function searchLatest(office,uf){
  if(!process.env.OPENAI_API_KEY)throw new Error('OPENAI_NOT_CONFIGURED');
  const today=new Intl.DateTimeFormat('pt-BR',{timeZone:'America/Sao_Paulo',dateStyle:'short'}).format(new Date()),target=targetFor(office,uf);
  const legislative=office.startsWith('DEPUTADO_');
  const prompt=`Hoje é ${today}. Encontre pesquisas eleitorais 2026 RECENTES e PUBLICADAS para ${target}. Use busca na web e confirme que cada levantamento possui registro válido no PesqEle/TSE no formato XX-00000/2026 ou BR-00000/2026. Priorize página do instituto, TSE e veículos jornalísticos reconhecidos. ${legislative?'Para deputados, aceite pesquisa espontânea, estimulada, regional ou de nomes somente se a metodologia realmente medir este cargo. NÃO transforme lembrança espontânea em intenção estimulada e NÃO crie ranking se a fonte não trouxer percentuais comparáveis.':'Para este cargo, use intenção de voto publicada e não misture cenários incompatíveis.'} Retorne no máximo as 6 pesquisas/levantamentos mais úteis e recentes. Retorne SOMENTE JSON: {"polls":[{"id":"...","institute":"Nome do instituto","published":"DD/MM/AAAA","field":"DD a DD/MM/AAAA","sample":1200,"margin":3,"registry":"XX-00000/2026","sourceUrl":"https://...","question":"texto curto da pergunta/cenário","mode":"Estimulada|Espontânea|Regional|Outro","results":[["Nome","Partido",12]]}]}. Se não conseguir confirmar fonte, registro e percentuais, omita. Não invente dados.`;
  const response=await fetch('https://api.openai.com/v1/responses',{method:'POST',headers:{'Content-Type':'application/json','Authorization':`Bearer ${process.env.OPENAI_API_KEY}`},body:JSON.stringify({model:MODEL,input:[{role:'system',content:'Você extrai pesquisas eleitorais brasileiras de fontes verificáveis. Preserve a metodologia original, devolva JSON estrito e nunca recomende voto.'},{role:'user',content:prompt}],tools:[{type:'web_search'}],max_output_tokens:2400,store:false})});
  const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(clean(data?.error?.message||`HTTP_${response.status}`));const parsed=parseJson(textFromResponse(data));return (Array.isArray(parsed.polls)?parsed.polls:[]).map(p=>normalizePoll(p,office,uf)).filter(Boolean)
}

export default async function handler(req,res){
  if(req.method!=='GET')return send(res,405,{ok:false,error:'METHOD_NOT_ALLOWED'},'no-store');
  let office=clean(String(req.query?.office||'PRESIDENTE').toUpperCase().replace(/[^A-Z_]/g,''),30);if(!OFFICES.has(office))office='PRESIDENTE';
  let uf=office==='PRESIDENTE'?'BR':clean(String(req.query?.uf||'MG').toUpperCase().replace(/[^A-Z]/g,''),2);
  if(office==='DEPUTADO_DISTRITAL'&&uf!=='DF')return send(res,200,{ok:true,fresh:false,office,uf,fetchedAt:new Date().toISOString(),polls:[],warning:'Deputado Distrital existe apenas no Distrito Federal.'});
  if(office==='DEPUTADO_ESTADUAL'&&uf==='DF')office='DEPUTADO_DISTRITAL';
  const fetchedAt=new Date().toISOString(),fallback=fallbackFor(office,uf);
  try{const freshPolls=await searchLatest(office,uf),polls=mergePolls(freshPolls,fallback);return send(res,200,{ok:true,fresh:freshPolls.length>0,office,uf,fetchedAt,polls,warning:polls.length?'':'Nenhuma pesquisa registrada e verificável encontrada para este cargo/UF.'})}
  catch(e){return send(res,200,{ok:true,fresh:false,office,uf,fetchedAt,polls:fallback,warning:fallback.length?'Atualização online indisponível; exibindo última carga válida.':'Nenhuma pesquisa registrada e verificável encontrada para este cargo/UF.',detail:clean(e?.message||e,160)})}
}
