const MODEL='gpt-5.4-nano';
const OFFICES=new Set(['PRESIDENTE','GOVERNADOR','SENADOR','DEPUTADO_FEDERAL','DEPUTADO_ESTADUAL','DEPUTADO_DISTRITAL']);
const UF_NAMES={AC:'Acre',AL:'Alagoas',AP:'Amapá',AM:'Amazonas',BA:'Bahia',CE:'Ceará',DF:'Distrito Federal',ES:'Espírito Santo',GO:'Goiás',MA:'Maranhão',MT:'Mato Grosso',MS:'Mato Grosso do Sul',MG:'Minas Gerais',PA:'Pará',PB:'Paraíba',PR:'Paraná',PE:'Pernambuco',PI:'Piauí',RJ:'Rio de Janeiro',RN:'Rio Grande do Norte',RS:'Rio Grande do Sul',RO:'Rondônia',RR:'Roraima',SC:'Santa Catarina',SP:'São Paulo',SE:'Sergipe',TO:'Tocantins'};

const PRESIDENT_FALLBACK=[
  {id:'df-br-2108',institute:'Datafolha',published:'21/08/2026',field:'18 a 20/08/2026',sample:2058,margin:2,registry:'BR-04496/2026',sourceUrl:'https://www1.folha.uol.com.br/poder/2026/08/datafolha-lula-marca-39-no-1o-turno-e-flavio-bolsonaro-tem-33.shtml',question:'Presidente - 1º turno',mode:'Estimulada',results:[['Lula','PT',39],['Flavio Bolsonaro','PL',33],['Ronaldo Caiado','PSD',5],['Renan Santos','Missao',4],['Romeu Zema','Novo',3],['Augusto Cury','Avante',2],['Branco/Nulo','',8],['Nao sabe','',3]]},
  {id:'quaest-br-1408',institute:'Quaest',published:'14/08/2026',field:'10 a 13/08/2026',sample:2004,margin:2,registry:'BR-06773/2026',sourceUrl:'https://quaest.com.br/relatorios/pesquisa-de-intencao-de-voto-para-presidente-1ot-rodada-1-14-08-2026/',question:'Presidente - 1º turno',mode:'Estimulada',results:[['Lula','PT',38],['Flavio Bolsonaro','PL',31],['Renan Santos','Missao',4],['Ronaldo Caiado','PSD',4],['Augusto Cury','Avante',2],['Romeu Zema','Novo',2],['Samara Martins','UP',1],['Branco/Nulo','',8],['Indecisos','',10]]}
];

const MG_GOVERNOR_FALLBACK=[
  {id:'quaest-mg-gov-2508',institute:'Quaest',published:'25/08/2026',field:'21 a 24/08/2026',sample:1506,margin:3,registry:'MG-04060/2026',sourceUrl:'https://noticias.uol.com.br/eleicoes/2026/08/25/quaest-mg-agosto.ghtm',question:'Governador de Minas Gerais - 1º turno',mode:'Estimulada',results:[['Cleitinho Azevedo','Republicanos',29],['Patrus Ananias','PT',11],['Alexandre Kalil','PDT',10],['Mateus Simões','PSD',7],['Gabriel Menezes','MDB',5],['Flávio Roscoe','PL',3],['Ben Mendes','Missão',2],['Professor Túlio Lopes','PCB',1],['Rafael Duda','PSTU',1],['Indecisos','',19],['Branco/Nulo/Não vai votar','',12]]},
  {id:'df-mg-gov-2108',institute:'Datafolha',published:'21/08/2026',field:'18 a 20/08/2026',sample:1204,margin:3,registry:'MG-00446/2026',sourceUrl:'https://www1.folha.uol.com.br/poder/2026/08/datafolha-cleitinho-lidera-disputa-em-mg-com-32-patrus-e-kalil-tem-12-cada.shtml',question:'Governador de Minas Gerais - 1º turno',mode:'Estimulada',results:[['Cleitinho Azevedo','Republicanos',32],['Patrus Ananias','PT',12],['Alexandre Kalil','PDT',12],['Mateus Simões','PSD',4],['Flávio Roscoe','PL',4],['Gabriel Azevedo','MDB',4],['Branco/Nulo','',14],['Indecisos','',13]]}
];

const MG_SENATE_FALLBACK=[
  {id:'quaest-mg-sen-2508',institute:'Quaest',published:'25/08/2026',field:'21 a 24/08/2026',sample:1506,margin:3,registry:'MG-04060/2026',sourceUrl:'https://noticias.uol.com.br/eleicoes/2026/08/25/quaest-mg-agosto.ghtm',question:'Senador por Minas Gerais - intenção de voto',mode:'Estimulada',results:[['Marília Campos','PT',15],['Carlos Viana','PSD',8],['Domingos Sávio','PL',8],['Marcelo Aro','PP',6],['Áurea Carolina','PSOL',2],['Marco Antônio Superman','Novo',2],['Carlin Moura','Avante',2],['Gustavo Galassi','PSDB',1],['Marcelo Heringer','PDT',1],['Ana Luiza do MLB','UP',1],['Manoel Carvalho','MDB',1],['Juiz Ramon Moreira','DC',1],['Indecisos','',31],['Branco/Nulo/Não vai votar','',21]]},
  {id:'df-mg-sen-2108',institute:'Datafolha',published:'21/08/2026',field:'18 a 20/08/2026',sample:1204,margin:3,registry:'MG-00446/2026',sourceUrl:'https://www1.folha.uol.com.br/poder/2026/08/datafolha-marilia-campos-tem-11-na-disputa-ao-senado-em-mg-viana-marca-8-e-domingos-savio-6.shtml',question:'Senador por Minas Gerais - intenção de voto',mode:'Estimulada',results:[['Marília Campos','PT',11],['Carlos Viana','PSD',8],['Domingos Sávio','PL',6],['Marcelo Aro','PP',5],['Ana Luiza do MLB','UP',4],['Marco Antônio Superman','Novo',3],['Áurea Carolina','PSOL',2],['Manoel Carvalho','MDB',2],['Gustavo Galassi','PSDB',2],['Tião Pessoa','PCO',2],['Marcelo Heringer','PDT',2],['Victória Mello Vic','PSTU',2],['Carlin Moura','Avante',1],['Juiz Ramon Moreira','DC',1],['Arcanjo Pimenta','MDB',1],['Fidélis Alcântara','UP',1],['Jordano Metalúrgico','PSTU',1],['Indecisos','',24],['Branco/Nulo','',21]]}
];

function send(res,status,body,cache='public, s-maxage=60, stale-while-revalidate=300'){res.statusCode=status;res.setHeader('Content-Type','application/json; charset=utf-8');res.setHeader('Cache-Control',cache);res.end(JSON.stringify(body))}
function clean(v,max=300){return String(v??'').replace(/[\u0000-\u001F\u007F]/g,' ').replace(/\s+/g,' ').trim().slice(0,max)}
function textFromResponse(data){if(typeof data?.output_text==='string'&&data.output_text.trim())return data.output_text.trim();const parts=[];for(const item of Array.isArray(data?.output)?data.output:[])for(const c of Array.isArray(item?.content)?item.content:[])if((c?.type==='output_text'||c?.type==='text')&&c.text)parts.push(c.text);return parts.join('\n').trim()}
function parseJson(text){const raw=String(text||'').trim().replace(/^```(?:json)?\s*/i,'').replace(/```$/,'').trim();const a=raw.indexOf('{'),b=raw.lastIndexOf('}');if(a<0||b<=a)throw new Error('NO_JSON');return JSON.parse(raw.slice(a,b+1))}
function dateScore(v){const m=String(v||'').match(/(\d{2})\/(\d{2})\/(\d{4})/);return m?Number(`${m[3]}${m[2]}${m[1]}`):0}
function safeUrl(url){const u=String(url||'');return /^https:\/\//i.test(u)&&!/(facebook\.com|instagram\.com|tiktok\.com|twitter\.com|x\.com)/i.test(u)?u:''}
function normalizePoll(p,office,uf){const institute=clean(p?.institute,80);if(!p||!institute)return null;const results=(Array.isArray(p.results)?p.results:[]).map(r=>[clean(r?.[0],90),clean(r?.[1],30),Number(r?.[2])]).filter(r=>r[0]&&Number.isFinite(r[2])&&r[2]>=0&&r[2]<=100);const registry=clean(p.registry,40),sourceUrl=safeUrl(p.sourceUrl);if(results.length<2||!sourceUrl||!/^([A-Z]{2}|BR)-\d{5}\/2026$/.test(registry))return null;return {id:clean(p.id||`${institute}-${office}-${uf}-${p.published||Date.now()}`,120),institute,office,uf,published:clean(p.published,20),field:clean(p.field,60),sample:Number(p.sample)||null,margin:Number(p.margin)||null,registry,sourceUrl,question:clean(p.question||'',150),mode:clean(p.mode||'',50),results}}
function fallbackFor(office,uf){if(office==='PRESIDENTE')return PRESIDENT_FALLBACK.map(p=>({...p,office:'PRESIDENTE',uf:'BR'}));if(office==='GOVERNADOR'&&uf==='MG')return MG_GOVERNOR_FALLBACK.map(p=>({...p,office:'GOVERNADOR',uf:'MG'}));if(office==='SENADOR'&&uf==='MG')return MG_SENATE_FALLBACK.map(p=>({...p,office:'SENADOR',uf:'MG'}));return []}
function mergePolls(fresh,fallback){const map=new Map();for(const p of [...fallback,...fresh]){const key=`${String(p.institute).toUpperCase()}|${p.mode||''}|${p.question||''}`;const old=map.get(key);if(!old||dateScore(p.published)>dateScore(old.published))map.set(key,p)}return [...map.values()].sort((a,b)=>dateScore(b.published)-dateScore(a.published)).slice(0,12)}
function targetFor(office,uf){const state=UF_NAMES[uf]||uf;if(office==='PRESIDENTE')return 'Presidente da República';if(office==='GOVERNADOR')return `Governador de ${state}`;if(office==='SENADOR')return `Senador por ${state}`;if(office==='DEPUTADO_FEDERAL')return `Deputado Federal por ${state}`;if(office==='DEPUTADO_DISTRITAL')return 'Deputado Distrital no Distrito Federal';return `Deputado Estadual por ${state}`}
async function searchLatest(office,uf){
  if(!process.env.OPENAI_API_KEY)throw new Error('OPENAI_NOT_CONFIGURED');
  const today=new Intl.DateTimeFormat('pt-BR',{timeZone:'America/Sao_Paulo',dateStyle:'short'}).format(new Date()),target=targetFor(office,uf);
  const legislative=office.startsWith('DEPUTADO_');
  const prompt=`Hoje é ${today}. Encontre pesquisas eleitorais 2026 RECENTES e PUBLICADAS para ${target}. Priorize levantamentos publicados HOJE e nas últimas 48 horas antes dos antigos. Faça busca ampla, sem se limitar a Datafolha e Quaest. Procure também AtlasIntel, Real Time Big Data, Paraná Pesquisas, Futura Inteligência, Instituto Veritá, Doxa, Nexus, Ipespe, Ipec e institutos regionais reconhecidos, além de páginas oficiais dos institutos, TSE/PesqEle e veículos jornalísticos confiáveis. Confirme que cada levantamento possui registro válido no TSE no formato XX-00000/2026 ou BR-00000/2026. ${legislative?'Para deputados, aceite pesquisa espontânea, estimulada, regional ou de nomes somente se a metodologia realmente medir este cargo. NÃO transforme lembrança espontânea em intenção estimulada e NÃO crie ranking se a fonte não trouxer percentuais comparáveis. Pesquise também imprensa regional do estado e do município quando o levantamento for territorialmente delimitado, deixando isso explícito em question/mode.':'Para este cargo, use intenção de voto publicada e não misture cenários incompatíveis.'} Retorne no máximo as 10 pesquisas/levantamentos mais úteis e recentes. Retorne SOMENTE JSON: {"polls":[{"id":"...","institute":"Nome do instituto","published":"DD/MM/AAAA","field":"DD a DD/MM/AAAA","sample":1200,"margin":3,"registry":"XX-00000/2026","sourceUrl":"https://...","question":"texto curto da pergunta/cenário","mode":"Estimulada|Espontânea|Regional|Outro","results":[["Nome","Partido",12]]}]}. Se não conseguir confirmar fonte, registro e percentuais, omita. Não invente dados.`;
  const response=await fetch('https://api.openai.com/v1/responses',{method:'POST',headers:{'Content-Type':'application/json','Authorization':`Bearer ${process.env.OPENAI_API_KEY}`},body:JSON.stringify({model:MODEL,input:[{role:'system',content:'Você extrai pesquisas eleitorais brasileiras de fontes verificáveis. Preserve a metodologia original, devolva JSON estrito e nunca recomende voto.'},{role:'user',content:prompt}],tools:[{type:'web_search'}],max_output_tokens:3400,store:false})});
  const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(clean(data?.error?.message||`HTTP_${response.status}`));const parsed=parseJson(textFromResponse(data));return (Array.isArray(parsed.polls)?parsed.polls:[]).map(p=>normalizePoll(p,office,uf)).filter(Boolean)
}

export default async function handler(req,res){
  if(req.method!=='GET')return send(res,405,{ok:false,error:'METHOD_NOT_ALLOWED'},'no-store');
  let office=clean(String(req.query?.office||'PRESIDENTE').toUpperCase().replace(/[^A-Z_]/g,''),30);if(!OFFICES.has(office))office='PRESIDENTE';
  let uf=office==='PRESIDENTE'?'BR':clean(String(req.query?.uf||'MG').toUpperCase().replace(/[^A-Z]/g,''),2);
  if(office==='DEPUTADO_DISTRITAL'&&uf!=='DF')return send(res,200,{ok:true,fresh:false,office,uf,fetchedAt:new Date().toISOString(),polls:[],warning:'Deputado Distrital existe apenas no Distrito Federal.'});
  if(office==='DEPUTADO_ESTADUAL'&&uf==='DF')office='DEPUTADO_DISTRITAL';
  const fetchedAt=new Date().toISOString(),fallback=fallbackFor(office,uf);
  try{const freshPolls=await searchLatest(office,uf),polls=mergePolls(freshPolls,fallback);return send(res,200,{ok:true,fresh:freshPolls.length>0,office,uf,fetchedAt,polls,warning:polls.length?'':'Nenhuma pesquisa registrada e verificável encontrada para este cargo/UF.'})}
  catch(e){return send(res,200,{ok:true,fresh:false,office,uf,fetchedAt,polls:fallback,warning:fallback.length?'Atualização online indisponível; exibindo última carga válida.':'Nenhuma pesquisa registrada e verificável encontrada para este cargo/UF.',detail:clean(e?.message||e,160)})}
}
