export function tseInt(v){return Number(String(v??'0').replace(/\./g,'').replace(',','.'))||0}
export function tsePct(v){return Number(String(v??'0').replace(',','.'))||0}
export function roundQE(vv,seats){if(seats<=0)return 0;const raw=vv/seats,f=Math.floor(raw);return raw-f>0.5?f+1:f}
function birthTimestamp(s){if(!s)return undefined;const m=/^(\d{2})\/(\d{2})\/(\d{4})$/.exec(String(s).trim());if(!m)return undefined;return Date.UTC(+m[3],+m[2]-1,+m[1])}
function candidateSort(a,b){if(b.votos!==a.votos)return b.votos-a.votos;const at=birthTimestamp(a.dataNascimento),bt=birthTimestamp(b.dataNascimento);if(at!==undefined&&bt!==undefined&&at!==bt)return at-bt;return a.nome.localeCompare(b.nome,'pt-BR')}
function validDest(c){return !c.destinacao||(/válid|valido/i.test(c.destinacao)&&!/anulad/i.test(c.destinacao))}
function candidateTieUndefined(a,b){if(!a||!b||a.votos!==b.votos)return false;const at=birthTimestamp(a.dataNascimento),bt=birthTimestamp(b.dataNascimento);return at===undefined||bt===undefined||at===bt}
function sortedCandidates(group,minVotes,electedIds){return group.candidatos.filter(c=>validDest(c)&&!electedIds.has(c.id)&&c.votos>=minVotes).slice().sort(candidateSort)}
function chooseCandidate(group,minVotes,electedIds){const candidates=sortedCandidates(group,minVotes,electedIds);return{candidates,candidate:candidates[0],tieUndefined:candidateTieUndefined(candidates[0],candidates[1])}}
function exactAverageCompare(a,b){const l=a.votos*b.divisor,r=b.votos*a.divisor;if(l!==r)return r-l;if(a.votos!==b.votos)return b.votos-a.votos;if((a.candidatoVotos??-1)!==(b.candidatoVotos??-1))return(b.candidatoVotos??-1)-(a.candidatoVotos??-1);return a.sigla.localeCompare(b.sigla,'pt-BR')}
function sameLegalPriority(a,b){if(!a||!b)return false;return a.votos*b.divisor===b.votos*a.divisor&&a.votos===b.votos&&(a.candidatoVotos??-1)===(b.candidatoVotos??-1)}
export function adaptUnified(raw,{electionCode,uf,cargoCode,photoBase='/api/tse?path='}){
 const parsed=raw||{},cargoRaw=(parsed.carg||[]).find(c=>String(c.cd)===String(cargoCode))||(parsed.carg||[])[0];if(!cargoRaw)throw new Error('Arquivo TSE sem cargo');
 const partidos=(cargoRaw.agr||[]).map((agr,ai)=>{const first=(agr.par||[])[0]||{},tipo=agr.tp==='f'?'federacao':'partido',sigla=agr.com||first.sg||agr.nm||`AGR ${ai+1}`,nome=agr.nm||first.nm||sigla;let nNom=0,nLeg=0;for(const p of agr.par||[]){nNom+=tseInt(p.tvtn);nLeg+=tseInt(p.tvtl)}const agrNom=tseInt(agr.tvtn),agrLeg=tseInt(agr.tvtl),votosNominais=agrNom>0?agrNom:nNom,votosLegenda=agrLeg>0?agrLeg:nLeg;const candidatos=[];for(const p of agr.par||[])for(const c of p.cand||[]){const abr=parsed.tpabr==='br'?'br':String(uf).toLowerCase();const path=`/oficial/ele2026/${electionCode}/fotos/${abr}/${c.sqcand}.jpeg`;candidatos.push({id:c.sqcand||`${p.n}-${c.n}-${c.seq}`,numero:c.n||'',nome:c.nmu||c.nm||'',partido:p.sg||p.nm||'',federacao:tipo==='federacao'?sigla:undefined,grupoId:agr.n||`agr-${ai}`,dataNascimento:c.dt||undefined,votos:tseInt(c.vap),pct:tsePct(c.pvap),eleitoTse:String(c.e).toLowerCase()==='s',situacaoOficial:(c.st||''),destinacao:c.dvt||p.dvt||'Válido',fotoUrl:photoBase+encodeURIComponent(path)})}candidatos.sort(candidateSort);return{id:agr.n||`agr-${ai}`,sigla,nome,tipo,composicao:agr.com||undefined,votosNominais,votosLegenda,votosValidos:votosNominais+votosLegenda,vagasOficiais:tseInt(agr.vag),candidatos}});
 const candidatos=partidos.flatMap(p=>p.candidatos).sort(candidateSort),s=parsed.s||{},e=parsed.e||{},v=parsed.v||{};
 return{cargoCode:String(cargoRaw.cd||cargoCode),abrangencia:String(uf).toUpperCase(),pctTotalizado:tsePct(s.pst),totalizadoEm:[parsed.dg,parsed.hg].filter(Boolean).join(' '),eleitorado:tseInt(e.te),comparecimento:tseInt(e.c),abstencao:tseInt(e.a),validos:tseInt(v.vv),brancos:tseInt(v.vb),nulos:tseInt(v.vn||v.tvn),vagas:tseInt(cargoRaw.nv),qe:tseInt(cargoRaw.qe),candidatos,partidos,meta:{awaiting:parsed.and==='n'||tsePct(s.pst)===0,turno:String(parsed.t||'1'),tf:String(parsed.tf||'n'),and:String(parsed.and||'n'),md:String(parsed.md||'n'),esae:String(parsed.esae||'n'),mnae:Array.isArray(parsed.mnae)?parsed.mnae:[],fase:String(parsed.f||'o'),idg:String(parsed.idg||''),dataGeracao:String(parsed.dg||''),horaGeracao:String(parsed.hg||'')}}}
}
export function calcularProporcional(resultado){
 const groups=resultado.partidos.filter(g=>g.votosValidos>0||g.candidatos.some(c=>c.votos>0)),seats=Math.max(0,Math.trunc(resultado.vagas)),vvFromGroups=groups.reduce((s,g)=>s+g.votosValidos,0),vv=Math.max(resultado.validos,vvFromGroups),qe=resultado.qe>0?Math.trunc(resultado.qe):roundQE(vv,seats),warnings=[],electedIds=new Set(),elected=[],actual=new Map(groups.map(g=>[g.id,0])),qpMap=new Map(),qpSeats=new Map(),sobra=new Map(groups.map(g=>[g.id,0])),rodadas=[];let blocked=false,identityUnresolved=false;
 const addPending=(id,n)=>{if(n>0)actual.set(id,(actual.get(id)||0)+n)},allocated=()=>[...actual.values()].reduce((a,b)=>a+b,0);
 if(!seats||!qe||!groups.length)return{vagas:seats,votosValidos:vv,qe,partidos:groups.map(g=>({id:g.id,sigla:g.sigla,nome:g.nome,votos:g.votosValidos,pctQE:0,qp:0,vagasQP:0,vagasSobra:0,total:g.vagasOficiais||0,oficial:g.vagasOficiais||0,apto80:false,candidatosElegiveis10:0,candidatosElegiveis20:0})),rodadas:[],eleitos:[],passos:[`Ainda não há votos válidos suficientes para calcular o QE. ${seats} vaga(s) estão previstas para este cargo.`],warnings,linhaDeCorte:{primeirosDeFora:[],primeirosSuplentesPorGrupo:[]}};
 const elect=(g,c,motivo,rodada)=>{if(!c||electedIds.has(c.id)||elected.length>=seats)return;electedIds.add(c.id);actual.set(g.id,(actual.get(g.id)||0)+1);elected.push({candidato:c,grupoId:g.id,grupoSigla:g.sigla,motivo,rodada})};
 const ten=qe*.10;for(const g of groups){const qp=Math.floor(g.votosValidos/qe);qpMap.set(g.id,qp);const cs=sortedCandidates(g,ten,electedIds),alloc=Math.min(qp,cs.length);let certain=alloc,pending=0;if(alloc>0&&alloc<cs.length&&candidateTieUndefined(cs[alloc-1],cs[alloc])){const tied=cs[alloc-1].votos;let start=alloc-1;while(start>0&&cs[start-1]?.votos===tied)start--;certain=start;pending=alloc-certain;identityUnresolved=true;blocked=true;warnings.push(`${g.sigla}: empate sem idade suficiente em ${pending} vaga(s) de QP.`)}qpSeats.set(g.id,alloc);cs.slice(0,certain).forEach(c=>elect(g,c,'QP'));addPending(g.id,pending);if(qp-alloc>0)warnings.push(`${g.sigla}: ${qp-alloc} vaga(s) de QP seguem para sobras por falta de candidato com 10% do QE.`)}
 let remaining=Math.max(0,seats-allocated()),roundNo=0;
 const runRound=phase=>{roundNo++;const entries=[],choices=new Map();for(const g of groups){const qp=qpMap.get(g.id)||0,sv=sobra.get(g.id)||0,divisor=qp+sv+1,threshold=phase==='fase 1'?qe*.20:0,choice=chooseCandidate(g,threshold,electedIds);choices.set(g.id,choice);const partyEligible=phase==='fase 1'?g.votosValidos>=qe*.80:true,candidateEligible=!!choice.candidate,apto=partyEligible&&candidateEligible;entries.push({grupoId:g.id,sigla:g.sigla,votos:g.votosValidos,divisor,vagasAteAgora:actual.get(g.id)||0,media:g.votosValidos/divisor,candidatoId:choice.candidate?.id,candidatoNome:choice.candidate?.nome,candidatoVotos:choice.candidate?.votos,apto,motivoInaptidao:!partyEligible?'menos de 80% do QE':!candidateEligible?(phase==='fase 1'?'sem candidato com 20% do QE':'sem candidato remanescente'):undefined})}const eligible=entries.filter(e=>e.apto).sort(exactAverageCompare),winner=eligible[0],runner=eligible[1];if(!winner){rodadas.push({rodada:roundNo,fase:phase,entries});return'no-eligible'}if(sameLegalPriority(winner,runner)){rodadas.push({rodada:roundNo,fase:phase,entries,empateIndefinido:true});warnings.push(`Empate indefinido na rodada ${roundNo}.`);return'blocked'}const g=groups.find(x=>x.id===winner.grupoId),choice=choices.get(g.id);if(choice.tieUndefined){addPending(g.id,1);sobra.set(g.id,(sobra.get(g.id)||0)+1);identityUnresolved=true;rodadas.push({rodada:roundNo,fase:phase,entries,vencedorId:g.id,vencedorSigla:g.sigla,empateIndefinido:true});return'blocked'}elect(g,choice.candidate,phase==='fase 1'?'média fase 1':'média final',roundNo);sobra.set(g.id,(sobra.get(g.id)||0)+1);rodadas.push({rodada:roundNo,fase:phase,entries,vencedorId:g.id,vencedorSigla:g.sigla,candidatoId:choice.candidate.id,candidatoNome:choice.candidate.nome});return'awarded'};
 if(!blocked)while(remaining>0){const o=runRound('fase 1');if(o==='awarded'){remaining--;continue}if(o==='blocked')blocked=true;break}if(!blocked)while(remaining>0){const o=runRound('final');if(o==='awarded'){remaining--;continue}if(o==='blocked')blocked=true;break}
 remaining=Math.max(0,seats-allocated());if(remaining>0)warnings.push(`${remaining} vaga(s) ficaram pendentes nos dados atuais.`);
 const partyRows=groups.map(g=>({id:g.id,sigla:g.sigla,nome:g.nome,votos:g.votosValidos,pctQE:qe?g.votosValidos/qe*100:0,qp:qpMap.get(g.id)||0,vagasQP:qpSeats.get(g.id)||0,vagasSobra:sobra.get(g.id)||0,total:actual.get(g.id)||0,oficial:g.vagasOficiais||0,apto80:g.votosValidos>=qe*.80,candidatosElegiveis10:g.candidatos.filter(c=>validDest(c)&&c.votos>=qe*.10).length,candidatosElegiveis20:g.candidatos.filter(c=>validDest(c)&&c.votos>=qe*.20).length})).sort((a,b)=>b.total-a.total||b.votos-a.votos);
 const unelected=groups.flatMap(g=>g.candidatos).filter(c=>validDest(c)&&!electedIds.has(c.id)).sort(candidateSort),electedByVotes=elected.slice().sort((a,b)=>candidateSort(a.candidato,b.candidato)),last=identityUnresolved?undefined:electedByVotes[electedByVotes.length-1],firstOut=identityUnresolved?undefined:unelected[0];
 return{vagas:seats,votosValidos:vv,qe,partidos:partyRows,rodadas,eleitos:elected,suplentes:identityUnresolved?[]:unelected,linhaDeCorte:{ultimoEleito:last,primeirosDeFora:identityUnresolved?[]:unelected.slice(0,5),diferencaVotos:last&&firstOut?Math.abs(last.candidato.votos-firstOut.votos):undefined,primeirosSuplentesPorGrupo:[]},passos:[`Foram considerados ${vv.toLocaleString('pt-BR')} votos válidos para ${seats} vaga(s).`,`O quociente eleitoral (QE) é ${qe.toLocaleString('pt-BR')} votos por cadeira.`,`O QP de cada grupo é piso(votos do grupo ÷ QE), com mínimo individual de 10% do QE.`,`As primeiras sobras exigem grupo com 80% do QE e candidatura com 20% do QE.`,`As sobras finais usam maiores médias entre grupos com candidatura remanescente.`],warnings}
}