const TSE='https://resultados.tse.jus.br';const UFS=['ac','al','ap','am','ba','ce','df','es','go','ma','mt','ms','mg','pa','pb','pr','pe','pi','rj','rn','rs','ro','rr','sc','sp','se','to'];
const FALLBACK={fed:'6257',est:'6259'};let cfgCache=globalThis.__ap26Cfg||null;let aggCache=globalThis.__ap26Agg||new Map();globalThis.__ap26Agg=aggCache;
function n(v){return Number(String(v??'0').replace(/\./g,'').replace(',','.'))||0}
function p(v){return Number(String(v??'0').replace(',','.'))||0}
async function codes(){if(cfgCache&&Date.now()-cfgCache.at<600000)return cfgCache.v;let v={...FALLBACK};try{const r=await fetch(TSE+'/oficial/comum/config/ele-c.json');if(r.ok){const j=await r.json();for(const pl of j.pl||[])if(pl.c==='ele2026')for(const e of pl.e||[]){const cs=new Set((e.abr||[]).flatMap(a=>(a.cp||[]).map(c=>String(c.cd))));if(cs.has('1'))v.fed=String(e.cd);if(cs.has('3')||cs.has('5')||cs.has('6'))v.est=String(e.cd)}}}catch{}cfgCache={at:Date.now(),v};globalThis.__ap26Cfg=cfgCache;return v}
function url(ele,uf,cargo){return `${TSE}/oficial/ele2026/${ele}/dados/${uf}/${uf}-c${String(cargo).padStart(4,'0')}-e${String(ele).padStart(6,'0')}-u.json`}
async function get(ele,uf,cargo){try{const r=await fetch(url(ele,uf,cargo),{headers:{accept:'application/json'}});return r.ok?await r.json():null}catch{return null}}
async function mapLimit(items,limit,fn){const out=new Array(items.length);let i=0;async function worker(){while(true){const idx=i++;if(idx>=items.length)return;out[idx]=await fn(items[idx],idx)}}await Promise.all(Array.from({length:Math.min(limit,items.length)},worker));return out}
function candList(d){const c=d?.carg?.[0],out=[];for(const a of c?.agr||[])for(const par of a.par||[])for(const x of par.cand||[])out.push({sqcand:String(x.sqcand||''),numero:String(x.n||''),nome:x.nmu||x.nm||'',partido:par.sg||'',grupo:a.com||par.sg||a.nm||'',votos:n(x.vap),pct:p(x.pvap),e:String(x.e||'n').toLowerCase()==='s',st:x.st||'',uf:String(d.cdabr||'').toUpperCase()});return out.sort((a,b)=>b.votos-a.votos||b.pct-a.pct)}
function groupRows(d){const c=d?.carg?.[0],rows=[];for(const a of c?.agr||[]){const first=(a.par||[])[0]||{};const sigla=a.com||first.sg||a.nm||'';let votes=n(a.tvtn)+n(a.tvtl);if(!votes)for(const par of a.par||[])votes+=n(par.tvtn)+n(par.tvtl);rows.push({id:String(a.n||sigla),sigla,nome:a.nm||first.nm||sigla,seats:n(a.vag),votes})}return rows}
export default async function handler(req,res){if(req.method!=='GET')return res.status(405).json({error:'Method not allowed'});const kind=String(req.query.kind||'camara');const key=kind;const hit=aggCache.get(key);if(hit&&Date.now()-hit.at<25000){res.setHeader('Cache-Control','public,s-maxage=20,stale-while-revalidate=40');return res.json(hit.data)}const c=await codes();const cargo=kind==='senado'?'5':'6';const docs=await mapLimit(UFS,4,uf=>get(c.est,uf,cargo));if(kind==='camara'){const groups=new Map();let seatsTotal=0,pst=0,loaded=0,sectionsTotal=0,sectionsDone=0;const official=[];for(let i=0;i<UFS.length;i++){const d=docs[i];if(!d)continue;loaded++;pst+=p(d.s?.pst);sectionsTotal+=n(d.s?.ts);sectionsDone+=n(d.s?.st);const cr=d.carg?.[0];seatsTotal+=n(cr?.nv);for(const g of groupRows(d)){const cur=groups.get(g.sigla)||{sigla:g.sigla,nome:g.nome,seats:0,votes:0};cur.seats+=g.seats;cur.votes+=g.votes;groups.set(g.sigla,cur)}for(const x of candList(d))if(x.e||/^Eleito/i.test(x.st))official.push(x)}const data={kind,updatedAt:new Date().toISOString(),ufsLoaded:loaded,ufsTotal:27,pctAverage:loaded?pst/loaded:0,sectionsTotal,sectionsDone,pctSections:sectionsTotal?sectionsDone/sectionsTotal*100:0,seatsTotal,officialSeats:[...groups.values()].sort((a,b)=>b.seats-a.seats||b.votes-a.votes),officialElected:official};aggCache.set(key,{at:Date.now(),data});res.setHeader('Cache-Control','public,s-maxage=20,stale-while-revalidate=40');return res.json(data)}else{const byParty=new Map(),ufs=[];let loaded=0,pst=0,officialCount=0,sectionsTotal=0,sectionsDone=0;for(let i=0;i<UFS.length;i++){const d=docs[i];if(!d)continue;loaded++;pst+=p(d.s?.pst);sectionsTotal+=n(d.s?.ts);sectionsDone+=n(d.s?.st);const cs=candList(d);const official=cs.filter(x=>x.e||/^Eleito/i.test(x.st));officialCount+=official.length;const leaders=cs.slice(0,2);for(const x of official){const cur=byParty.get(x.partido)||{sigla:x.partido,seats:0};cur.seats++;byParty.set(x.partido,cur)}ufs.push({uf:UFS[i].toUpperCase(),pct:p(d.s?.pst),tf:d.tf||'n',official:official.map(x=>({...x,official:true})),leaders:leaders.map(x=>({...x,official:false}))})}const data={kind,updatedAt:new Date().toISOString(),ufsLoaded:loaded,ufsTotal:27,pctAverage:loaded?pst/loaded:0,sectionsTotal,sectionsDone,pctSections:sectionsTotal?sectionsDone/sectionsTotal*100:0,seatsContested:54,officialCount,byParty:[...byParty.values()].sort((a,b)=>b.seats-a.seats),ufs};aggCache.set(key,{at:Date.now(),data});res.setHeader('Cache-Control','public,s-maxage=20,stale-while-revalidate=40');return res.json(data)}}
